package de.act.central.types;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


/**
 * CAbstractAttachment generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("unchecked")
public class Attachment extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 2122630322375696423L;
	transient private Long attId = null;
	private String fid;
	private String attType;
	private Short attNo;
	private Integer addId;
	private String auth;
	private String sign;
	private Date corr;
	private Set<FormularSLI> FSlis = new HashSet<FormularSLI>(0);
	private Set<Routing> FRts = new HashSet<Routing>(0);
	private Set<PackageState> FPkgStats = new HashSet<PackageState>(0);
	private Set<PackageItemAVI> FAviItems = new HashSet<PackageItemAVI>(0);
	private Set<BookingFlightState> FBkgFltStats = new HashSet<BookingFlightState>(0);
	private Set<AccountingInformation> FAcis = new HashSet<AccountingInformation>(0);
	private Set<FormularBKG> FBkgs = new HashSet<FormularBKG>(0);
	private Set<BookingFlight> FBkgFlts = new HashSet<BookingFlight>(0);
	private Set<PackageItemBKG> FBkgItems = new HashSet<PackageItemBKG>(0);
	private Set<FomularDGR> FDgrs = new HashSet<FomularDGR>(0);
	private Set<Addresses> FAdds = new HashSet<Addresses>(0);
	private Set<PackageItemAWB> FAwbItems = new HashSet<PackageItemAWB>(0);
	private Set<Acceptance> FAccs = new HashSet<Acceptance>(0);
	private Set<FAccHeader> FAccHeader = new HashSet<FAccHeader>(0);
	private Set<PackageItem> FPkgs = new HashSet<PackageItem>(0);
	private Set<PackageItemSLI> FSliItems = new HashSet<PackageItemSLI>(0);
	private Set<PackageItemDGR> FDgrItems = new HashSet<PackageItemDGR>(0);
	private Set<FormularAVI> FAvis = new HashSet<FormularAVI>(0);
	private Set<AwbState> FAwbStats = new HashSet<AwbState>(0);
	private Set<FormularAWB> FAwbs = new HashSet<FormularAWB>(0);
	private Set<OtherCharges> FOts = new HashSet<OtherCharges>(0);

	// Constructors

	/** default constructor */
	public Attachment() {

	}

	/** full constructor */
	public Attachment(String fid, String attType, Short attNo, Integer addId, String auth, Date corr, Set FSlis, Set FRts, Set FPkgStats, Set FAviItems, Set FBkgFltStats, Set FAcis, Set FBkgs, Set FBkgFlts, Set FBkgItems, Set FDgrs, Set FAdds, Set FAwbItems, Set FAccs, Set FPkgs, Set FDgrItems, Set FAvis, Set FAwbStats, Set FAwbs) {
		this.fid = fid;
		this.attType = attType;
		this.attNo = attNo;
		this.addId = addId;
		this.auth = auth;
		this.corr = corr;
		this.FSlis = FSlis;
		this.FRts = FRts;
		this.FPkgStats = FPkgStats;
		this.FAviItems = FAviItems;
		this.FBkgFltStats = FBkgFltStats;
		this.FAcis = FAcis;
		this.FBkgs = FBkgs;
		this.FBkgFlts = FBkgFlts;
		this.FBkgItems = FBkgItems;
		this.FDgrs = FDgrs;
		this.FAdds = FAdds;
		this.FAwbItems = FAwbItems;
		this.FAccs = FAccs;
		this.FPkgs = FPkgs;
		this.FDgrItems = FDgrItems;
		this.FAvis = FAvis;
		this.FAwbStats = FAwbStats;
		this.FAwbs = FAwbs;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 * f_id, att_type, att_no, add_id
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Attachment)) { return false; }
		if (this == obj) { return true; }
		Attachment rhs = (Attachment) obj;
		return new EqualsBuilder().append(this.fid, rhs.fid).append(this.attType, rhs.attType).append(this.attNo, rhs.attNo).append(this.addId, rhs.addId).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.fid).append(this.attType).append(this.attNo).append(this.addId).toHashCode();
	}

	// Property accessors

	public Long getAttId() {
		return this.attId;
	}

	public void setAttId(Long attId) {
		this.attId = attId;
	}

	public String getFid() {
		return this.fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public String getAttType() {
		return this.attType;
	}

	public void setAttType(String attType) {
		this.attType = attType;
	}

	public Short getAttNo() {
		return this.attNo;
	}

	public void setAttNo(Short attNo) {
		this.attNo = attNo;
	}

	public Integer getAddId() {
		return this.addId;
	}

	public void setAddId(Integer addId) {
		this.addId = addId;
	}

	public String getAuth() {
		return this.auth;
	}

	public void setAuth(String auth) {
		this.auth = auth;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public final String getSign() {
		return this.sign;
	}

	public final void setSign(String sign) {
		this.sign = sign;
	}

	public final Set<Acceptance> getFAccs() {
		return this.FAccs;
	}

	public final void setFAccs(Set<Acceptance> accs) {
		this.FAccs = accs;
	}

	public Set<FAccHeader> getFAccHeader() {
		return FAccHeader;
	}

	public void setFAccHeader(Set<FAccHeader> accHeader) {
		FAccHeader = accHeader;
	}

	public final Set<AccountingInformation> getFAcis() {
		return this.FAcis;
	}

	public final void setFAcis(Set<AccountingInformation> acis) {
		this.FAcis = acis;
	}

	public final Set<Addresses> getFAdds() {
		return this.FAdds;
	}

	public final void setFAdds(Set<Addresses> adds) {
		this.FAdds = adds;
	}

	public final Set<PackageItemAVI> getFAviItems() {
		return this.FAviItems;
	}

	public final void setFAviItems(Set<PackageItemAVI> aviItems) {
		this.FAviItems = aviItems;
	}

	public final Set<FormularAVI> getFAvis() {
		return this.FAvis;
	}

	public final void setFAvis(Set<FormularAVI> avis) {
		this.FAvis = avis;
	}

	public final Set<PackageItemAWB> getFAwbItems() {
		return this.FAwbItems;
	}

	public final void setFAwbItems(Set<PackageItemAWB> awbItems) {
		this.FAwbItems = awbItems;
	}

	public final Set<FormularAWB> getFAwbs() {
		return this.FAwbs;
	}

	public final void setFAwbs(Set<FormularAWB> awbs) {
		this.FAwbs = awbs;
	}

	public final Set<AwbState> getFAwbStats() {
		return this.FAwbStats;
	}

	public final void setFAwbStats(Set<AwbState> awbStats) {
		this.FAwbStats = awbStats;
	}

	public final Set<BookingFlight> getFBkgFlts() {
		return this.FBkgFlts;
	}

	public final void setFBkgFlts(Set<BookingFlight> bkgFlts) {
		this.FBkgFlts = bkgFlts;
	}

	public final Set<BookingFlightState> getFBkgFltStats() {
		return this.FBkgFltStats;
	}

	public final void setFBkgFltStats(Set<BookingFlightState> bkgFltStats) {
		this.FBkgFltStats = bkgFltStats;
	}

	public final Set<PackageItemBKG> getFBkgItems() {
		return this.FBkgItems;
	}

	public final void setFBkgItems(Set<PackageItemBKG> bkgItems) {
		this.FBkgItems = bkgItems;
	}

	public final Set<FormularBKG> getFBkgs() {
		return this.FBkgs;
	}

	public final void setFBkgs(Set<FormularBKG> bkgs) {
		this.FBkgs = bkgs;
	}

	public final Set<PackageItemDGR> getFDgrItems() {
		return this.FDgrItems;
	}

	public final void setFDgrItems(Set<PackageItemDGR> dgrItems) {
		this.FDgrItems = dgrItems;
	}

	public final Set<FomularDGR> getFDgrs() {
		return this.FDgrs;
	}

	public final void setFDgrs(Set<FomularDGR> dgrs) {
		this.FDgrs = dgrs;
	}

	public final Set<PackageItem> getFPkgs() {
		return this.FPkgs;
	}

	public final void setFPkgs(Set<PackageItem> pkgs) {
		this.FPkgs = pkgs;
	}

	public final Set<PackageState> getFPkgStats() {
		return this.FPkgStats;
	}

	public final void setFPkgStats(Set<PackageState> pkgStats) {
		this.FPkgStats = pkgStats;
	}

	public final Set<Routing> getFRts() {
		return this.FRts;
	}

	public final void setFRts(Set<Routing> rts) {
		this.FRts = rts;
	}

	public final Set<FormularSLI> getFSlis() {
		return this.FSlis;
	}

	public final void setFSlis(Set<FormularSLI> slis) {
		this.FSlis = slis;
	}

	public Set<OtherCharges> getFOts() {
		return this.FOts;
	}

	public void setFOts(Set<OtherCharges> ots) {
		this.FOts = ots;
	}

	public Set<PackageItemSLI> getFSliItems() {
		return FSliItems;
	}

	public void setFSliItems(Set<PackageItemSLI> sliItems) {
		FSliItems = sliItems;
	}

	public void setNewCreatorAndId(Integer address) {
		Date d = new Date();
		this.setAttId(null);
		this.setCorr(d);
		this.setAddId(address);
		this.attNo++;
	}

	public void setNewCreatorAndId(Integer address, String ap_3lc) {
		Date d = new Date();
		this.setAttId(null);
		this.setCorr(d);
		this.setAddId(address);
		this.attNo++;  
		if (this.FAccs != null){
			for(Acceptance acc:this.FAccs){
				if (acc != null){
					acc.setConAddId(address);
					acc.setAp3lc(ap_3lc);
					acc.setAccId(null);
					acc.setCorr(d);
					acc.setStatId(null); // acceptancestatus auf null setzen, bedeutet noch nicht akzeptiert.
					acc.setStatDescr(null);
					Set<AcceptanceItem> shps = acc.getFAccItems();
					if (shps != null){
						for(AcceptanceItem accshp:shps){
							accshp.setAccItemId(null);
							accshp.setLocId(null);
						}
					}
				}
			}
		}
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.attId);
		sb.append(" [");
		sb.append(this.attType);
		sb.append(",");
		sb.append(this.attNo);
		sb.append(",");
		sb.append(this.auth);
		sb.append(",");
		sb.append(this.addId);
		sb.append("]");
		return sb.toString();
	}

	public void setNewId() {
		Date d = new Date();
		this.setAttId(null);
		this.setCorr(d);
		this.attNo++;
		if (this.FBkgFlts!=null) {
			for(BookingFlight f: FBkgFlts) {
				f.setBkgFltId(null);
				f.setCorr(d);
			}
		}

		if (this.FBkgFltStats!=null) {
			for(BookingFlightState f: FBkgFltStats) {
				f.setBkgFltStatId(null);
				f.setCorr(d);
			}
		}
	}
}