package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * AwbNo generated by MyEclipse - Hibernate Tools
 */

public class AwbNo extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 1379183501008350337L;
	private String FId;
	private FormularInformation FForm;
	private String ca3dg;
	private String ffw3lc;
	private Short awbStock;
	private Short awbNo;
	private String non_standard;
	private Date corr;

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.FId);
		sb.append(" [");
		sb.append(this.ca3dg);sb.append(", ");
		sb.append(this.ffw3lc);sb.append(", ");
		sb.append(this.awbStock);sb.append(", ");
		sb.append(this.awbNo);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public AwbNo() {
		
	}

	/** minimal constructor */
	public AwbNo(FormularInformation FForm) {
		this.FForm = FForm;
	}

	/** full constructor */
	public AwbNo(FormularInformation FForm, String ca3dg, String ffw3lc, Short awbStock, Short awbNo, Date corr) {
		this.FForm = FForm;
		this.ca3dg = ca3dg;
		this.ffw3lc = ffw3lc;
		this.awbStock = awbStock;
		this.awbNo = awbNo;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 * ca_3dg, ffw_3lc, awb_stock, awb_no
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof AwbNo)) { return false; }
		if (this == obj) { return true; }
		AwbNo rhs = (AwbNo) obj;
		return new EqualsBuilder().append(this.ca3dg, rhs.ca3dg).append(this.ffw3lc, rhs.ffw3lc).append(this.awbStock, rhs.awbStock).append(this.awbNo, rhs.awbNo).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.awbNo).append(this.awbStock).append(this.ffw3lc).append(this.ca3dg).toHashCode();
	}

	// Property accessors

	public String getFId() {
		return this.FId;
	}

	public void setFId(String FId) {
		this.FId = FId;
	}

	public FormularInformation getFForm() {
		return this.FForm;
	}

	public void setFForm(FormularInformation FForm) {
		this.FForm = FForm;
	}

	public String getCa3dg() {
		return this.ca3dg;
	}

	public void setCa3dg(String ca3dg) {
		this.ca3dg = ca3dg;
	}

	public String getFfw3lc() {
		return this.ffw3lc;
	}

	public void setFfw3lc(String ffw3lc) {
		this.ffw3lc = ffw3lc;
	}

	public Short getAwbStock() {
		return this.awbStock;
	}

	public void setAwbStock(Short awbStock) {
		this.awbStock = awbStock;
	}

	public Short getAwbNo() {
		return this.awbNo;
	}

	public void setAwbNo(Short awbNo) {
		this.awbNo = awbNo;
	}

	public String getNon_standard() {
		return non_standard;
	}

	public void setNon_standard(String non_standard) {
		this.non_standard = non_standard;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
}