package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * BookingFlightState generated by MyEclipse - Hibernate Tools
 */

public class BookingFlightState2 extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -8681778665544020734L;
	transient private Long bkgFltStatId;
	private BookingFlight2 FBkgFlt;
	private Attachment2 FAtt;
	private String bkgStatus;
	private String statDescr;
	private Date corr;

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.bkgFltStatId);
		sb.append(" [");
		sb.append(this.bkgStatus);sb.append(", ");
		sb.append(this.statDescr);sb.append(", {");
		sb.append(this.FAtt);sb.append("}, ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public BookingFlightState2() {
		
	}

	/** full constructor */
	public BookingFlightState2(BookingFlight2 FBkgFlt, Attachment2 FAtt, String bkgStatus, String statDescr, Date corr) {
		this.FBkgFlt = FBkgFlt;
		this.FAtt = FAtt;
		this.bkgStatus = bkgStatus;
		this.statDescr = statDescr;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof BookingFlightState2)) { return false; }
		if (this == obj) { return true; }
		BookingFlightState2 rhs = (BookingFlightState2) obj;
		return new EqualsBuilder().append(this.FBkgFlt, rhs.FBkgFlt).append(this.FAtt, rhs.FAtt).append(this.bkgStatus, rhs.bkgStatus).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FBkgFlt).append(this.FAtt).append(this.bkgStatus).toHashCode();
	}

	// Property accessors

	public Long getBkgFltStatId() {
		return this.bkgFltStatId;
	}

	public void setBkgFltStatId(Long bkgFltStatId) {
		this.bkgFltStatId = bkgFltStatId;
	}

	public BookingFlight2 getFBkgFlt() {
		return this.FBkgFlt;
	}

	public void setFBkgFlt(BookingFlight2 FBkgFlt) {
		this.FBkgFlt = FBkgFlt;
	}

	public Attachment2 getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment2 FAtt) {
		this.FAtt = FAtt;
	}

	public String getBkgStatus() {
		return this.bkgStatus;
	}

	public void setBkgStatus(String bkgStatus) {
		this.bkgStatus = bkgStatus;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
}