package de.act.central.types;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * CentralSubt generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("unchecked")
public class CentralSubt extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 431616922149316575L;
	transient private Long subtId;
	private String subtType;
	private String subtIataCode;
	private String subtDgrRefNo;
	private String subtCompany;
	private String subtStreet;
	private String subtPlace;
	private String subtCountry;
	private Date subtCorr;
	private Set FDgrsForShpSubtId = new HashSet(0);
	private Set FSubtTcoms = new HashSet(0);
	private Set FAddsForShpSubtId = new HashSet(0);
	private Set FAvis = new HashSet(0);
	private Set FDgrsForConSubtId = new HashSet(0);
	private Set FAddsForFfwSubtId = new HashSet(0);
	private Set FAddsForConSubtId = new HashSet(0);
	private Set FAccs = new HashSet(0);

	// Constructors

	/** default constructor */
	public CentralSubt() {
		
	}

	/** full constructor */
	public CentralSubt(String subtType, String subtIataCode, String subtDgrRefNo, String subtCompany, String subtStreet, String subtPlace, String subtCountry, Date subtCorr, Set FDgrsForShpSubtId, Set FSubtTcoms, Set FAddsForShpSubtId, Set FAvis, Set FDgrsForConSubtId, Set FAddsForFfwSubtId, Set FAddsForConSubtId, Set FAccs) {
		this.subtType = subtType;
		this.subtIataCode = subtIataCode;
		this.subtDgrRefNo = subtDgrRefNo;
		this.subtCompany = subtCompany;
		this.subtStreet = subtStreet;
		this.subtPlace = subtPlace;
		this.subtCountry = subtCountry;
		this.subtCorr = subtCorr;
		this.FDgrsForShpSubtId = FDgrsForShpSubtId;
		this.FSubtTcoms = FSubtTcoms;
		this.FAddsForShpSubtId = FAddsForShpSubtId;
		this.FAvis = FAvis;
		this.FDgrsForConSubtId = FDgrsForConSubtId;
		this.FAddsForFfwSubtId = FAddsForFfwSubtId;
		this.FAddsForConSubtId = FAddsForConSubtId;
		this.FAccs = FAccs;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof CentralSubt)) { return false; }
		if (this == obj) { return true; }
		CentralSubt rhs = (CentralSubt) obj;
		return new EqualsBuilder().append(this.subtCompany, rhs.subtCompany).append(this.subtCountry, rhs.subtCountry).append(this.subtStreet, rhs.subtStreet).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.subtCountry).append(this.subtStreet).append(this.subtCompany).toHashCode();
	}

	// Property accessors

	public Long getSubtId() {
		return this.subtId;
	}

	public void setSubtId(Long subtId) {
		this.subtId = subtId;
	}

	public String getSubtType() {
		return this.subtType;
	}

	public void setSubtType(String subtType) {
		this.subtType = subtType;
	}

	public String getSubtIataCode() {
		return this.subtIataCode;
	}

	public void setSubtIataCode(String subtIataCode) {
		this.subtIataCode = subtIataCode;
	}

	public String getSubtDgrRefNo() {
		return this.subtDgrRefNo;
	}

	public void setSubtDgrRefNo(String subtDgrRefNo) {
		this.subtDgrRefNo = subtDgrRefNo;
	}

	public String getSubtCompany() {
		return this.subtCompany;
	}

	public void setSubtCompany(String subtCompany) {
		this.subtCompany = subtCompany;
	}

	public String getSubtStreet() {
		return this.subtStreet;
	}

	public void setSubtStreet(String subtStreet) {
		this.subtStreet = subtStreet;
	}

	public String getSubtPlace() {
		return this.subtPlace;
	}

	public void setSubtPlace(String subtPlace) {
		this.subtPlace = subtPlace;
	}

	public String getSubtCountry() {
		return this.subtCountry;
	}

	public void setSubtCountry(String subtCountry) {
		this.subtCountry = subtCountry;
	}

	public Date getSubtCorr() {
		return this.subtCorr;
	}

	public void setSubtCorr(Date subtCorr) {
		this.subtCorr = subtCorr;
	}

	public Set getFDgrsForShpSubtId() {
		return this.FDgrsForShpSubtId;
	}

	public void setFDgrsForShpSubtId(Set FDgrsForShpSubtId) {
		this.FDgrsForShpSubtId = FDgrsForShpSubtId;
	}

	public Set getFSubtTcoms() {
		return this.FSubtTcoms;
	}

	public void setFSubtTcoms(Set FSubtTcoms) {
		this.FSubtTcoms = FSubtTcoms;
	}

	public Set getFAddsForShpSubtId() {
		return this.FAddsForShpSubtId;
	}

	public void setFAddsForShpSubtId(Set FAddsForShpSubtId) {
		this.FAddsForShpSubtId = FAddsForShpSubtId;
	}

	public Set getFAvis() {
		return this.FAvis;
	}

	public void setFAvis(Set FAvis) {
		this.FAvis = FAvis;
	}

	public Set getFDgrsForConSubtId() {
		return this.FDgrsForConSubtId;
	}

	public void setFDgrsForConSubtId(Set FDgrsForConSubtId) {
		this.FDgrsForConSubtId = FDgrsForConSubtId;
	}

	public Set getFAddsForFfwSubtId() {
		return this.FAddsForFfwSubtId;
	}

	public void setFAddsForFfwSubtId(Set FAddsForFfwSubtId) {
		this.FAddsForFfwSubtId = FAddsForFfwSubtId;
	}

	public Set getFAddsForConSubtId() {
		return this.FAddsForConSubtId;
	}

	public void setFAddsForConSubtId(Set FAddsForConSubtId) {
		this.FAddsForConSubtId = FAddsForConSubtId;
	}

	public Set getFAccs() {
		return this.FAccs;
	}

	public void setFAccs(Set FAccs) {
		this.FAccs = FAccs;
	}
}