package de.act.central.types;

/**
 * CentralDistribution generated by MyEclipse - Hibernate Tools
 */

public class CentralDistribution extends Central implements java.io.Serializable {

	// Fields
	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -6493957348588326911L;
	private CentralDistributionId id;
	private String addId; //HENRY this should either Long or Integer
	private String addType;
	private String writer;

	// Constructors

	/** default constructor */
	public CentralDistribution() {
		
	}

	/** full constructor */
	public CentralDistribution(String addId, String addType, String writer) {
		this.addId = addId;
		this.addType = addType;
		this.writer = writer;
	}

	// Property accessors

	public CentralDistributionId getId() {
		return this.id;
	}

	public void setId(CentralDistributionId id) {
		this.id = id;
	}

	public String getAddId() {
		return this.addId;
	}

	public void setAddId(String addId) {
		this.addId = addId;
	}

	public String getAddType() {
		return this.addType;
	}

	public void setAddType(String addType) {
		this.addType = addType;
	}

	public String getWriter() {
		return this.writer;
	}

	public void setWriter(String writer) {
		this.writer = writer;
	}
}