package de.act.central.types;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * FormularInformation generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("unchecked")
public class FormularInformation extends Central implements java.io.Serializable, Cloneable {
	// Fields
	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long        serialVersionUID = -1971951782979008204L;
	private String                   FId;
	private Long 					 creatorId;
	private FormularInformation      FForm;
	private String                   FLevel;
	private Short                    FChildren;
	private String                   name;
	private Integer                  readOnly         = 0;
	private Integer                  isLocal          = 1;
	private String                   status;
	private String                   statId;
	private String                   statDescr;
	private Date                     setStamp         = new Date();
	private Date                     created          = new Date();
	private String                   formularName;
	private String                   workState;
	private String                   caId             = "00";
	private AwbNo                    awbNo;
	private Set<FormularInformation> FForms           = new HashSet<FormularInformation>(0);
	private Set<Distribution>        CDistrs          = new HashSet<Distribution>(0);
	private Set<CentralDistribution> FDistrs          = new HashSet<CentralDistribution>(0);
	private Set<Attachment>          FAtts            = new HashSet<Attachment>(0);
	private boolean 				 anyBooking;
	
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.FId);
		sb.append(" [{");
		sb.append(this.awbNo);sb.append("}, ");
		sb.append(this.formularName);sb.append(", ");
		sb.append(this.workState);sb.append(", ");
		sb.append(this.caId);
		sb.append("]");
		return sb.toString();
	}

	// Constructors
	/** default constructor */
	public FormularInformation() {
		
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public Object clone() throws CloneNotSupportedException {
		FormularInformation parent = null;
		if (FForm != null) parent = (FormularInformation) FForm.clone();
		FormularInformation f = new FormularInformation(parent, this.FId, this.FLevel, new Short(FChildren), name, new Integer(readOnly), new Integer(isLocal), status, statId, statDescr, setStamp, created, formularName, workState, caId, awbNo, FForms, CDistrs, FDistrs, FAtts , creatorId);
		return f;
	}

	/** full constructor */
	public FormularInformation(FormularInformation FForm, String Fid, String FLevel, Short FChildren, String name, Integer readOnly, Integer isLocal, String status, String statId, String statDescr,
			Date setStamp, Date created, String formularName, String workState, String caId, AwbNo awbno, Set FForms, Set CDistrs, Set FDistrs, Set FAtts,Long creatorID) {
		this.FForm = FForm;
		this.FLevel = FLevel;
		this.FId = Fid;
		this.FChildren = FChildren;
		this.name = name;
		this.readOnly = readOnly;
		this.isLocal = isLocal;
		this.status = status;
		this.statId = statId;
		this.statDescr = statDescr;
		this.setStamp = setStamp;
		this.created = created;
		this.formularName = formularName;
		this.workState = workState;
		this.caId = caId;
		this.awbNo = awbno;
		this.FForms = FForms;
		this.CDistrs = CDistrs;
		this.FDistrs = FDistrs;
		this.FAtts = FAtts;
		this.creatorId = creatorID;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof FormularInformation)){
			return false;
		}
		if (this == obj){
			return true;
		}
		FormularInformation rhs = (FormularInformation) obj;
		return new EqualsBuilder().append(this.FId, rhs.FId).isEquals();
	}

	/**
	 * 12.12.2005
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FId).toHashCode();
	}

	// Property accessors
	public String getFId() {
		return this.FId;
	}

	public void setFId(String FId) {
		this.FId = FId;
	}

	public FormularInformation getFForm() {
		return this.FForm;
	}

	public void setFForm(FormularInformation FForm) {
		this.FForm = FForm;
	}

	public String getFLevel() {
		return this.FLevel;
	}

	public void setFLevel(String FLevel) {
		this.FLevel = FLevel;
	}

	public Short getFChildren() {
		return this.FChildren;
	}

	public void setFChildren(Short FChildren) {
		this.FChildren = FChildren;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatId() {
		return this.statId;
	}

	public void setStatId(String statId) {
		this.statId = statId;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public Date getSetStamp() {
		return this.setStamp;
	}

	public void setSetStamp(Date setStamp) {
		this.setStamp = setStamp;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getFormularName() {
		return this.formularName;
	}

	public void setFormularName(String formularName) {
		this.formularName = formularName;
	}

	public String getWorkState() {
		return this.workState;
	}

	public void setWorkState(String workState) {
		this.workState = workState;
	}

	public String getCaId() {
		return this.caId;
	}

	public void setCaId(String caId) {
		this.caId = caId;
	}

	 public AwbNo getAwbNo() {
		return this.awbNo;
	}

	 public void setAwbNo(AwbNo awbNo) {
		 this.awbNo = awbNo;
	 }

	 public void setFAtts(Set<Attachment> atts) {
		 this.FAtts = atts;
	 }

	 public void setFForms(Set<FormularInformation> forms) {
		 this.FForms = forms;
	 }

	 public Set<Distribution> getCDistrs() {
		 return this.CDistrs;
	 }

	 public void setCDistrs(Set<Distribution> distrs) {
		 this.CDistrs = distrs;
	 }

	 public Set<CentralDistribution> getFDistrs() {
		 return this.FDistrs;
	 }

	 public void setFDistrs(Set<CentralDistribution> distrs) {
		 this.FDistrs = distrs;
	 }

	 public Set<Attachment> getFAtts() {
		 return this.FAtts;
	 }

	 public Set<FormularInformation> getFForms() {
		 return this.FForms;
	 }

	 public Integer getIsLocal() {
		 return this.isLocal;
	 }

	 public void setIsLocal(Integer isLocal) {
		 this.isLocal = isLocal;
	 }

	 public Integer getReadOnly() {
		 return this.readOnly;
	 }

	 public void setReadOnly(Integer readOnly) {
		 this.readOnly = readOnly;
	 }

	 public Long getCreatorId() {
		 return this.creatorId;
	 }

	 public void setCreatorId(Long creatorId) {
		 this.creatorId = creatorId;
	 }

	 public boolean anyBooking() {
		 return anyBooking;
	 }

	 public void anyBooking(boolean anyBooking) {
		 this.anyBooking = anyBooking;
	 }
}