package de.act.central.types;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * FormularBKG generated by MyEclipse - Hibernate Tools
 */

public class FormularBKG extends Central implements java.io.Serializable {
	
	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -4246514777109409275L;
	transient private Long attId;
	private Sticker sticker;
	private Attachment FAtt;

	// Constructors

	/** default constructor */
	public FormularBKG() {
		
	}

	/** minimal constructor */
	public FormularBKG(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	/** full constructor */
	public FormularBKG(Sticker FStick, Attachment FAtt) {
		this.sticker = FStick;
		this.FAtt = FAtt;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof FormularBKG)) { return false; }
		if (this == obj) { return true; }
		FormularBKG rhs = (FormularBKG) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).toHashCode();
	}

	// Property accessors

	public Long getAttId() {
		return this.attId;
	}

	public void setAttId(Long attId) {
		this.attId = attId;
	}

	public Sticker getSticker() {
		return this.sticker;
	}

	public void setSticker(Sticker FStick) {
		this.sticker = FStick;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}
}