package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * OtherCharges generated by MyEclipse - Hibernate Tools
 */

public class OtherCharges extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 3460269113926328199L;
	transient private Long otId;
	private Attachment FAtt;
	private String ot2lc;
	private String ot1lc;
	private Double otRate;
	private Date corr;
	private String otCur3lcFrom;
	private String otCur3lcTo;
	private Double otConversionRate;

	// Constructors

	/** default constructor */
	public OtherCharges() {
		
	}

	/** full constructor */
	public OtherCharges(Attachment FAwb, String ot2lc, String ot1lc, Double otRate, Date corr) {
		this.FAtt = FAwb;
		this.ot2lc = ot2lc;
		this.ot1lc = ot1lc;
		this.otRate = otRate;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof OtherCharges)) { return false; }
		if (this == obj) { return true; }
		OtherCharges rhs = (OtherCharges) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.ot2lc, rhs.ot2lc).append(this.ot1lc, rhs.ot1lc).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.ot2lc).append(this.ot1lc).toHashCode();
	}
	// Property accessors

	public Long getOtId() {
		return this.otId;
	}

	public void setOtId(Long otId) {
		this.otId = otId;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment att) {
		this.FAtt = att;
	}

	public String getOt2lc() {
		return this.ot2lc;
	}

	public void setOt2lc(String ot2lc) {
		this.ot2lc = ot2lc;
	}

	public String getOt1lc() {
		return this.ot1lc;
	}

	public void setOt1lc(String ot1lc) {
		this.ot1lc = ot1lc;
	}

	public Double getOtRate() {
		return this.otRate;
	}

	public void setOtRate(Double otRate) {
		this.otRate = otRate;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public String getOtCur3lcFrom() {
		return otCur3lcFrom;
	}

	public void setOtCur3lcFrom(String otCur3lcFrom) {
		this.otCur3lcFrom = otCur3lcFrom;
	}

	public String getOtCur3lcTo() {
		return otCur3lcTo;
	}

	public void setOtCur3lcTo(String otCur3lcTo) {
		this.otCur3lcTo = otCur3lcTo;
	}

	public Double getOtConversionRate() {
		return otConversionRate;
	}

	public void setOtConversionRate(Double otConversionRate) {
		this.otConversionRate = otConversionRate;
	}
}