package de.act.central.types;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * PackageItem generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("unused")
public class PackageItemSLI extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 08.01.2007
	 */
	private static final long serialVersionUID = 5943103611345910535L;
	transient private Long pkgId;
	private PackageItemAWB FAwbItem;
	private Sticker sticker;
	private Uld AUld;
	private Attachment FAtt;
	private Short rowNo;
	private String marks;
	private Integer pcs;
	private Integer pkgsPltsd;
	private String pkgsCol;
	private String pkgsMat;
	private String pkgsShp;
	private Long comId;
	private Long annId;
	private Double wgt;
	private Long l;
	private Long w;
	private Long h;
	private String scc3lc;
	private Date corr;
	private Set<PackageState> FPkgStats = new HashSet<PackageState>(0);
	private Set<PackageItemAVI> FAviItems = new HashSet<PackageItemAVI>(0);
	private Set<PackageItemDGR> FDgrItems = new HashSet<PackageItemDGR>(0);
	private Set<AcceptanceItem> FAccPkgs = new HashSet<AcceptanceItem>(0);

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.pkgId);
		sb.append(" [");
		sb.append(this.rowNo);sb.append(", ");
		sb.append(this.pcs);sb.append(", ");
		sb.append(this.wgt);sb.append(", ");
		sb.append(this.comId);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public PackageItemSLI() {

	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof PackageItemSLI)) { return false; }
		if (this == obj) { return true; }
		PackageItemSLI rhs = (PackageItemSLI) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.rowNo, rhs.rowNo).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.rowNo).toHashCode();
	}

	// Property accessors

	public Long getPkgId() {
		return this.pkgId;
	}

	public void setPkgId(Long pkgId) {
		this.pkgId = pkgId;
	}

	public PackageItemAWB getFAwbItem() {
		return this.FAwbItem;
	}

	public void setFAwbItem(PackageItemAWB FAwbItem) {
		this.FAwbItem = FAwbItem;
	}

	public Sticker getSticker() {
		return this.sticker;
	}

	public void setSticker(Sticker FStick) {
		this.sticker = FStick;
	}

	public Uld getAUld() {
		return this.AUld;
	}

	public void setAUld(Uld AUld) {
		this.AUld = AUld;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public Short getRowNo() {
		return this.rowNo;
	}

	public void setRowNo(Short rowNo) {
		this.rowNo = rowNo;
	}

	public String getMarks() {
		return this.marks;
	}

	public void setMarks(String marks) {
		this.marks = marks;
	}

	public Integer getPcs() {
		return this.pcs;
	}

	public void setPcs(Integer pcs) {
		this.pcs = pcs;
	}

	public Integer getPkgsPltsd() {
		return this.pkgsPltsd;
	}

	public void setPkgsPltsd(Integer pkgsPltsd) {
		this.pkgsPltsd = pkgsPltsd;
	}

	public String getPkgsCol() {
		return this.pkgsCol;
	}

	public void setPkgsCol(String pkgsCol) {
		this.pkgsCol = pkgsCol;
	}

	public String getPkgsMat() {
		return this.pkgsMat;
	}

	public void setPkgsMat(String pkgsMat) {
		this.pkgsMat = pkgsMat;
	}

	public String getPkgsShp() {
		return this.pkgsShp;
	}

	public void setPkgsShp(String pkgsShp) {
		this.pkgsShp = pkgsShp;
	}

	public Long getComId() {
		return this.comId;
	}

	public void setComId(Long comId) {
		this.comId = comId;
	}

	public Long getAnnId() {
		return this.annId;
	}

	public void setAnnId(Long annId) {
		this.annId = annId;
	}

	public Double getWgt() {
		return this.wgt;
	}

	public void setWgt(Double wgt) {
		this.wgt = wgt;
	}

	public Long getL() {
		return this.l;
	}

	public void setL(Long l) {
		this.l = l;
	}

	public Long getW() {
		return this.w;
	}

	public void setW(Long w) {
		this.w = w;
	}

	public Long getH() {
		return this.h;
	}

	public void setH(Long h) {
		this.h = h;
	}

	public String getScc3lc() {
		return this.scc3lc;
	}

	public void setScc3lc(String scc3lc) {
		this.scc3lc = scc3lc;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	//    public Set getFPkgStats() {
	//        return this.FPkgStats;
	//    }
	//
	//    public void setFPkgStats(Set FPkgStats) {
	//        this.FPkgStats = FPkgStats;
	//    }

	//    public Set getFAviItems() {
	//        return this.FAviItems;
	//    }
	//
	//    public void setFAviItems(Set FAviItems) {
	//        this.FAviItems = FAviItems;
	//    }

	//    public Set getFDgrItems() {
	//        return this.FDgrItems;
	//    }
	//
	//    public void setFDgrItems(Set FDgrItems) {
	//        this.FDgrItems = FDgrItems;
	//    }
	//
	//    public Set getFAccPkgs() {
	//        return this.FAccPkgs;
	//    }
	//
	//    public void setFAccPkgs(Set FAccPkgs) {
	//        this.FAccPkgs = FAccPkgs;
	//    }
}