package de.act.common.types.nonstaticobjects;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import de.act.common.types.attachment.CAbstractAttachment;

/**
 * AwbState generated by MyEclipse - Hibernate Tools
 */

public class AwbState implements java.io.Serializable {

	private static final long serialVersionUID = 6684515563469402468L;
	// Fields
	private Long id = -1L;
	private CAbstractAttachment attachment;
	private String awbStatus;
	private String statDescr;
	private RFStick sticker;
	private Date corr;

	// Constructors

	/** default constructor */
	public AwbState() {
		
	}

	/** minimal constructor */
	public AwbState(CAbstractAttachment attachment) {
		this.attachment = attachment;
	}

	/** full constructor */
	public AwbState(CAbstractAttachment attachment, String awbStatus, String statDescr, RFStick sticker, Date corr) {
		this.attachment = attachment;
		this.awbStatus = awbStatus;
		this.statDescr = statDescr;
		this.sticker = sticker;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj== this)return true;
		if (obj instanceof AwbState) {
			AwbState s = (AwbState) obj;
			return new EqualsBuilder().append(this.attachment, s.attachment).append(this.awbStatus, s.awbStatus).append(this.statDescr, s.statDescr).append(this.sticker, s.sticker).append(this.corr, s.corr).isEquals();
		}
		return false;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.attachment).append(this.awbStatus).append(this.statDescr).append(this.sticker).append(this.corr).toHashCode();
	}

	public String getAwbStatus() {
		return this.awbStatus;
	}

	public void setAwbStatus(String awbStatus) {
		this.awbStatus = awbStatus;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public CAbstractAttachment getAttachment() {
		return attachment;
	}

	public void setAttachment(CAbstractAttachment attachment) {
		this.attachment = attachment;
		this.id = attachment.getId();
	}

	public Long getId() {
		//if (id>=0) {
			return id;
		//}
		//else
		//	return this.attachment.getId();
	}

	public void setId(Long id) {
		this.id = id;
	}

	public RFStick getSticker() {
		return sticker;
	}

	public void setSticker(RFStick sticker) {
		this.sticker = sticker;
	}
}