package de.act.common.types.nonstaticobjects;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import de.act.common.types.attachment.CAbstractAttachment;
import de.act.common.types.attachment.CPackageAttachment;
import de.act.common.types.packageitems.ItemPKG;

/**
 * PackageState generated by MyEclipse - Hibernate Tools
 */

public class PackageState  implements java.io.Serializable {

	private static final long serialVersionUID = -5081532018606835600L;
	// Fields
	private Long pkgStatId = -1L;
	private CAbstractAttachment attachment;
	private String pkgStatus;
	private String statDescr;
	private String addId;
	private Date corr;
	private ItemPKG itemPKG;

	// Constructors

	/** default constructor */
	public PackageState() {
		attachment = new CPackageAttachment();
	}

	/** full constructor */
	public PackageState(CAbstractAttachment attachment, ItemPKG pkgId, String pkgStatus, String statDescr, String addId, Date corr) {
		this.attachment = attachment;
		this.itemPKG = pkgId;
		this.pkgStatus = pkgStatus;
		this.statDescr = statDescr;
		this.addId = addId;
		this.corr = corr;
	}

	// Property accessors
	public Long getPkgStatId() {
		return this.pkgStatId;
	}

	public void setPkgStatId(Long pkgStatId) {
		this.pkgStatId = pkgStatId;
	}

	public  CAbstractAttachment getAttachment() {
		return attachment;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 * att_id, pkg_id, pkg_status
	 */
	@Override
	public boolean equals(Object obj) {
		if (obj==this)return true;
		if (obj instanceof PackageState){
			PackageState p = (PackageState) obj;
			return new EqualsBuilder().append(this.attachment, p.attachment).append(this.itemPKG, p.itemPKG).append(this.pkgStatus,p.pkgStatus).isEquals();
		}
		return false;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.attachment).append(this.itemPKG).append(this.pkgStatus).toHashCode();
	}

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 08.11.2006
	 * @param attachment The attachment to set.
	 */
	public  void setAttachment(CAbstractAttachment attachment) {
		this.attachment = attachment;
		this.pkgStatId = attachment.getId();
	}

	public String getPkgStatus() {
		return this.pkgStatus;
	}

	public void setPkgStatus(String pkgStatus) {
		this.pkgStatus = pkgStatus;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public String getAddId() {
		return this.addId;
	}

	public void setAddId(String addId) {
		this.addId = addId;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public  ItemPKG getItemSLI() {
		return itemPKG;
	}
	
	public  void setItemSLI(ItemPKG itemPKG) {
		this.itemPKG = itemPKG;
	}
}