package de.act.central.types;

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * AcceptanceItem generated by MyEclipse - Hibernate Tools
 */

public class AcceptanceItem extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 1547622047715846292L;
	transient private Long accItemId;
	private Uld AUld;
	private Long bkgItemId; //transient 
	private Acceptance FAcc;
	private Short rowNo;
	private Integer awbAcc;
	private Short sliRow;
	private String marks;
	private Integer pcs;
	private Integer pkgsPltsd;
	private String pkgsCol;
	private String pkgsMat;
	private String pkgsShp;
	private Long comId;
	private Long annId;
	private Double wgt;
	private Long l;
	private Long w;
	private Long h;
	private String scc3lc;
	transient private Integer locId;
	private ManifestItem maniItem = null;
	private Set<Discrepencies> FDiscrs = new HashSet<Discrepencies>(0);
	private Set<AcceptancePackage> FAccPkgs = new HashSet<AcceptancePackage>(0);     
	
	// Constructors

	/** default constructor */
	public AcceptanceItem() {
		
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof AcceptanceItem)) { return false; }
		if (this == obj) { return true; }
		AcceptanceItem rhs = (AcceptanceItem) obj;
		return new EqualsBuilder().append(this.FAcc, rhs.FAcc).append(this.rowNo, rhs.rowNo).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAcc).append(this.rowNo).toHashCode();
	}

	// Property accessors

	public Long getAccItemId() {
		return this.accItemId;
	}

	public void setAccItemId(Long accItemId) {
		this.accItemId = accItemId;
	}

	public Uld getAUld() {
		return this.AUld;
	}

	public void setAUld(Uld AUld) {
		this.AUld = AUld;
	}

	public Long getBkgItemId() {
		return bkgItemId;
	}

	public void setBkgItemId(Long bkgItemId) {
		this.bkgItemId = bkgItemId;
	}

	public Acceptance getFAcc() {
		return this.FAcc;
	}

	public void setFAcc(Acceptance FAcc) {
		this.FAcc = FAcc;
	}

	public Short getRowNo() {
		return this.rowNo;
	}

	public void setRowNo(Short rowNo) {
		this.rowNo = rowNo;
	}

	public Integer getAwbAcc() {
		return awbAcc;
	}

	public void setAwbAcc(Integer awbAcc) {
		this.awbAcc = awbAcc;
	}

	public Short getSliRow() {
		return this.sliRow;
	}

	public void setSliRow(Short sliRow) {
		this.sliRow = sliRow;
	}

	public String getMarks() {
		return this.marks;
	}

	public void setMarks(String marks) {
		this.marks = marks;
	}

	public Integer getPcs() {
		return this.pcs;
	}

	public void setPcs(Integer pcs) {
		this.pcs = pcs;
	}

	public Integer getPkgsPltsd() {
		return this.pkgsPltsd;
	}

	public void setPkgsPltsd(Integer pkgsPltsd) {
		this.pkgsPltsd = pkgsPltsd;
	}

	public String getPkgsCol() {
		return this.pkgsCol;
	}

	public void setPkgsCol(String pkgsCol) {
		this.pkgsCol = pkgsCol;
	}

	public String getPkgsMat() {
		return this.pkgsMat;
	}

	public void setPkgsMat(String pkgsMat) {
		this.pkgsMat = pkgsMat;
	}

	public String getPkgsShp() {
		return this.pkgsShp;
	}

	public void setPkgsShp(String pkgsShp) {
		this.pkgsShp = pkgsShp;
	}

	public Long getComId() {
		return this.comId;
	}

	public void setComId(Long comId) {
		this.comId = comId;
	}

	public Long getAnnId() {
		return this.annId;
	}

	public void setAnnId(Long annId) {
		this.annId = annId;
	}

	public Double getWgt() {
		return this.wgt;
	}

	public void setWgt(Double wgt) {
		this.wgt = wgt;
	}

	public Long getL() {
		return this.l;
	}

	public void setL(Long l) {
		this.l = l;
	}

	public Long getW() {
		return this.w;
	}

	public void setW(Long w) {
		this.w = w;
	}

	public Long getH() {
		return this.h;
	}

	public void setH(Long h) {
		this.h = h;
	}

	public String getScc3lc() {
		return this.scc3lc;
	}

	public void setScc3lc(String scc3lc) {
		this.scc3lc = scc3lc;
	}

	public Integer getLocId() {
		return this.locId;
	}

	public void setLocId(Integer locId) {
		this.locId = locId;
	}

	 public Set<AcceptancePackage> getFAccPkgs() {
		return this.FAccPkgs;
	}

	 public Set<Discrepencies> getFDiscrs() {
		return this.FDiscrs;
	}

	 public  void setFAccPkgs(Set<AcceptancePackage> accPkgs) {
		 this.FAccPkgs = accPkgs;
	 }

	 public  void setFDiscrs(Set<Discrepencies> discrs) {
		 this.FDiscrs = discrs;
	 }

	 public ManifestItem getManiItem() {
		 return maniItem;
	 }

	 public void setManiItem(ManifestItem maniItem) {
		 this.maniItem = maniItem;
	 }
}