package de.act.central.types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Acceptance generated by MyEclipse - Hibernate Tools
 */

public class Acceptance extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -4713314464609986633L;
	transient private Long accId;
	private Sticker sticker;
	private Attachment FAtt;
	private CentralSubt FSubt;
	private Integer awbAcc;
	private String apDept;
	private String ap3lc;
	private String apDest;
	private Integer conAddId;
	private String statId;
	private String statDescr;
	private String sign;
	private String card;
	private Date corr;
	private Set<AcceptanceItem> FAccItems = new HashSet<AcceptanceItem>(0);
	private List<AcceptanceItem> listAccItem = new ArrayList<AcceptanceItem>();

	// Constructors

	/** default constructor */
	public Acceptance() {
		
	}

	// Property accessors

	public Long getAccId() {
		return this.accId;
	}

	public void setAccId(Long accId) {
		this.accId = accId;
	}

	public Sticker getSticker() {
		return this.sticker;
	}

	public void setSticker(Sticker FStick) {
		this.sticker = FStick;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public CentralSubt getFSubt() {
		return this.FSubt;
	}

	public void setFSubt(CentralSubt FSubt) {
		this.FSubt = FSubt;
	}

	public Integer getAwbAcc() {
		return this.awbAcc;
	}

	public void setAwbAcc(Integer awbAcc) {
		this.awbAcc = awbAcc;
	}

	public String getApDept() {
		return this.apDept;
	}

	public void setApDept(String apDept) {
		this.apDept = apDept;
	}

	public String getAp3lc() {
		return this.ap3lc;
	}

	public void setAp3lc(String ap3lc) {
		this.ap3lc = ap3lc;
	}

	public String getApDest() {
		return this.apDest;
	}

	public void setApDest(String apDest) {
		this.apDest = apDest;
	}

	public Integer getConAddId() {
		return this.conAddId;
	}

	public void setConAddId(Integer conAddId) {
		this.conAddId = conAddId;
	}

	public String getStatId() {
		return this.statId;
	}

	public void setStatId(String statId) {
		this.statId = statId;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public final Set<AcceptanceItem> getFAccItems() {
		return this.FAccItems;
	}
	 
	 public final void setFAccItems(Set<AcceptanceItem> accItems) {
		 this.FAccItems = accItems;
	 }

	 public List<AcceptanceItem> getListAccItem() {
		return listAccItem;
	}

	public void setListAccItem(List<AcceptanceItem> listAccItem) {
		this.listAccItem = listAccItem;
	}

	/* (non-Javadoc)
	  * @see java.lang.Object#equals(java.lang.Object)
	  */
	 @Override
	 public boolean equals(Object obj) {
		 if (!(obj instanceof Acceptance)) { return false; }
		 if (this == obj) { return true; }
		 Acceptance rhs = (Acceptance) obj;
		 return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.awbAcc, rhs.awbAcc).isEquals();
	 }

	 /**
	  * 12.12.2005
	  *
	  * @see java.lang.Object#hashCode()
	  */
	 @Override
	 public int hashCode() {
		 return new HashCodeBuilder().append(this.FAtt).append(this.awbAcc).toHashCode();
	 }
}