package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * AccountingInformation generated by MyEclipse - Hibernate Tools
 */

public class AccountingInformation extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 9164826842533233288L;
	transient private Long id;
	private Attachment FAtt;
	private Short aciSeq;
	private String aciId;
	private String aciRem;
	private Date corr;

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.id);
		sb.append(" [{");
		sb.append(this.FAtt);sb.append("}, ");
		sb.append(this.aciSeq);sb.append(", ");
		sb.append(this.aciId);sb.append(", ");
		sb.append(this.aciRem);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public AccountingInformation() {

	}

	/** full constructor */
	public AccountingInformation(String aciId, String aciRem, Date corr) {
		this.aciId = aciId;
		this.aciRem = aciRem;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 * f_id, att_type, att_no, add_id
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof AccountingInformation)) { return false; }
		if (this == obj) { return true; }
		AccountingInformation rhs = (AccountingInformation) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.aciSeq, rhs.aciSeq).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.aciSeq).toHashCode();
	}

	public String getAciId() {
		return this.aciId;
	}

	public void setAciId(String aciId) {
		this.aciId = aciId;
	}

	public String getAciRem() {
		return this.aciRem;
	}

	public void setAciRem(String aciRem) {
		this.aciRem = aciRem;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public Short getAciSeq() {
		return aciSeq;
	}

	public void setAciSeq(Short aciSeq) {
		this.aciSeq = aciSeq;
	}

	public Attachment getFAtt() {
		return FAtt;
	}

	public void setFAtt(Attachment att) {
		FAtt = att;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
}