package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * AwbState generated by MyEclipse - Hibernate Tools
 */

public class AwbState extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -1013118593447438501L;
	transient private Long attachment;
	private Sticker sticker;
	private Attachment FAtt;
	private String awbStatus;
	private String statDescr;
	private Date corr;

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.attachment);
		sb.append(" [");
		sb.append(this.awbStatus);sb.append(", ");
		sb.append(this.statDescr);sb.append(", {");
		sb.append(this.FAtt);sb.append("}, ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public AwbState() {
		
	}

	/** minimal constructor */
	public AwbState(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	/** full constructor */
	public AwbState(Sticker FStick, Attachment FAtt, String awbStatus, String statDescr, Date corr) {
		this.sticker = FStick;
		this.FAtt = FAtt;
		this.awbStatus = awbStatus;
		this.statDescr = statDescr;
		this.corr = corr;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof AwbState)) { return false; }
		if (this == obj) { return true; }
		AwbState rhs = (AwbState) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).toHashCode();
	}
	// Property accessors

	public Long getAttachment() {
		return this.attachment;
	}

	public void setAttachment(Long attachment) {
		this.attachment = attachment;
	}

	public Sticker getSticker() {
		return this.sticker;
	}

	public void setSticker(Sticker FStick) {
		this.sticker = FStick;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public String getAwbStatus() {
		return this.awbStatus;
	}

	public void setAwbStatus(String awbStatus) {
		this.awbStatus = awbStatus;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
}