package de.act.central.types;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * CentralUser generated by MyEclipse - Hibernate Tools
 */

public class CentralUser extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -6225034051161489401L;
	private String addId; //HENRY this should be either Long or Integer
	private String password;
	private String subject;

	// Constructors

	/** default constructor */
	public CentralUser() {
		
	}

	/** full constructor */
	public CentralUser(String password, String subject) {
		this.password = password;
		this.subject = subject;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof CentralUser)) { return false; }
		if (this == obj) { return true; }
		CentralUser rhs = (CentralUser) obj;
		return new EqualsBuilder().append(this.addId, rhs.addId).append(this.subject, rhs.subject).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.addId).append(this.subject).toHashCode();
	}

	// Property accessors

	public String getAddId() {
		return this.addId;
	}

	public void setAddId(String addId) {
		this.addId = addId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}
}