package de.act.central.types;

/**
 * CentralFlights generated by MyEclipse - Hibernate Tools
 */

public class CentralAircraft extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 7426575423504796815L;
	private int ac_id;
	private String ac_reg;
	private String name;
	private String ca_id;
	private int ac_type_id;
	private String ac_cargo;
	private String vad_id;

	// Constructors

	/** default constructor */
	public CentralAircraft() {
		
	}

	/** full constructor */
	public CentralAircraft(int ac_id, String ac_reg, String name, String ca_id, int ac_type_id, String ac_cargo, String vad_id) {
		this.ac_id = ac_id;
		this.ac_reg = ac_reg;
		this.name = name;
		this.ca_id = ca_id;
		this.ac_type_id = ac_type_id;
		this.ac_cargo = ac_cargo;
		this.vad_id = vad_id;
	}

	// Property accessors

	public int getAc_id() {
		return ac_id;
	}

	public void setAc_id(int ac_id) {
		this.ac_id = ac_id;
	}

	public String getAc_reg() {
		return ac_reg;
	}

	public void setAc_reg(String ac_reg) {
		this.ac_reg = ac_reg;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCa_id() {
		return ca_id;
	}

	public void setCa_id(String ca_id) {
		this.ca_id = ca_id;
	}

	public int getAc_type_id() {
		return ac_type_id;
	}

	public void setAc_type_id(int ac_type_id) {
		this.ac_type_id = ac_type_id;
	}

	public String getAc_cargo() {
		return ac_cargo;
	}

	public void setAc_cargo(String ac_cargo) {
		this.ac_cargo = ac_cargo;
	}

	public String getVad_id() {
		return vad_id;
	}

	public void setVad_id(String vad_id) {
		this.vad_id = vad_id;
	}
}