package de.act.central.types;

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CentralFlights generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("unchecked")
public class CFlt extends Central implements java.io.Serializable {

	private static final long serialVersionUID = -933590605177272287L;
	private Long fltId;
	private Long SFltId;
	private Date fltDate;
	private Double maxWgt;
	private Double maxVol;
	private Set CBkgs = new HashSet(0);
	private Long flt_group;
	private Timestamp dep;
	private Timestamp arr;
	private Long ac;

	/** default constructor */
	public CFlt() {
		
	}

	/** full constructor */
	public CFlt(Long SFltId, Date fltDate, Double maxWgt, Double maxVol, Set CBkgs) {
		this.SFltId = SFltId;
		this.fltDate = fltDate;
		this.maxWgt = maxWgt;
		this.maxVol = maxVol;
		this.CBkgs = CBkgs;
	}

	public Long getFltId() {
		return this.fltId;
	}

	public void setFltId(Long fltId) {
		this.fltId = fltId;
	}

	public Long getSFltId() {
		return this.SFltId;
	}

	public void setSFltId(Long SFltId) {
		this.SFltId = SFltId;
	}

	public Date getFltDate() {
		return this.fltDate;
	}

	public void setFltDate(Date fltDate) {
		this.fltDate = fltDate;
	}

	public Double getMaxWgt() {
		return this.maxWgt;
	}

	public void setMaxWgt(Double maxWgt) {
		this.maxWgt = maxWgt;
	}

	public Double getMaxVol() {
		return this.maxVol;
	}

	public void setMaxVol(Double maxVol) {
		this.maxVol = maxVol;
	}

	public Set getCBkgs() {
		return this.CBkgs;
	}

	public void setCBkgs(Set CBkgs) {
		this.CBkgs = CBkgs;
	}

	public Long getFlt_group() {
		return flt_group;
	}

	public void setFlt_group(Long flt_group) {
		this.flt_group = flt_group;
	}

	public Timestamp getDep() {
		return dep;
	}

	public void setDep(Timestamp dep) {
		this.dep = dep;
	}

	public Timestamp getArr() {
		return arr;
	}

	public void setArr(Timestamp arr) {
		this.arr = arr;
	}

	public Long getAc() {
		return ac;
	}

	public void setAc(Long ac) {
		this.ac = ac;
	}
}