package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Distribution generated by MyEclipse - Hibernate Tools
 */

public class Distribution extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 8410021300599710442L;
	transient private String id;
	private String fid;
	private String addId; //HENRY this should be either Long or Integer
	private String addType;
	private Integer part = 0;
	private Date rcvd;
	private Date sent;
	private Integer writer;

	// Constructors

	/** default constructor */
	public Distribution() {
		
	}

	/** full constructor */
	public Distribution(String addId, String addType, Date rcvd, Date sent, Integer writer) {
		this.addId = addId;
		this.addType = addType;
		this.rcvd = rcvd;
		this.sent = sent;
		this.writer = writer;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Distribution)) { return false; }
		if (this == obj) { return true; }
		Distribution rhs = (Distribution) obj;
		return new EqualsBuilder().append(this.fid, rhs.fid).append(this.addId, rhs.addId).append(this.addType, rhs.addType).append(this.part, rhs.part).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.fid).append(this.addId).append(this.addType).append(this.part).toHashCode();
	}
	// Property accessors

	public String getAddId() {
		return this.addId;
	}

	public void setAddId(String addId) {
		this.addId = addId;
	}

	public String getAddType() {
		return this.addType;
	}

	public void setAddType(String addType) {
		this.addType = addType;
	}

	public Date getRcvd() {
		return this.rcvd;
	}

	public void setRcvd(Date rcvd) {
		this.rcvd = rcvd;
	}

	public Date getSent() {
		return this.sent;
	}

	public void setSent(Date sent) {
		this.sent = sent;
	}

	public Integer getWriter() {
		return this.writer;
	}

	public void setWriter(Integer writer) {
		this.writer = writer;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getPart() {
		return part;
	}

	public void setPart(Integer part) {
		this.part = part;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}
}