package de.act.central.types;

import java.util.Date;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

import de.act.common.types.handling.ANotocItem;
import de.act.common.types.packageitems.ItemAWBAccount;

/**
 * FormularAWB generated by MyEclipse - Hibernate Tools
 */

public class FormularAWB extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 3843056790159750164L;
	transient private Long attId;
	private Attachment FAtt;
	private Double curRate;
	private Double insuRate;
	private String ccdId;
	private Double wgtChrg;
	private Double valChrg;
	private Double tax;
	private Double curConvRate;
	private Date awbDate;
	private String awbPlace;
	private String signShp;
	private String signAir;
	private String card;
	private Date corr;
	private String mrnNo;
	private Set<ItemAWBAccount> fAwbAccount;

	// Constructors

	/** default constructor */
	public FormularAWB() {
		
	}

	/** minimal constructor */
	public FormularAWB(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	/** full constructor */
	public FormularAWB(Attachment FAtt, Double curRate, Double insuRate, String ccdId, Double wgtChrg, Double valChrg, Double tax, Double curConvRate, Date awbDate, String awbPlace, String signShp, String signAir, String card, Date corr, String mrnNo) {
		this.FAtt = FAtt;
		this.curRate = curRate;
		this.insuRate = insuRate;
		this.ccdId = ccdId;
		this.wgtChrg = wgtChrg;
		this.valChrg = valChrg;
		this.tax = tax;
		this.curConvRate = curConvRate;
		this.awbDate = awbDate;
		this.awbPlace = awbPlace;
		this.signShp = signShp;
		this.signAir = signAir;
		this.card = card;
		this.corr = corr;
		this.mrnNo = mrnNo;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof FormularAWB)) { return false; }
		if (this == obj) { return true; }
		FormularAWB rhs = (FormularAWB) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).toHashCode();
	}

	// Property accessors

	public Long getAttId() {
		return this.attId;
	}

	public void setAttId(Long attId) {
		this.attId = attId;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public Double getCurRate() {
		return this.curRate;
	}

	public void setCurRate(Double curRate) {
		this.curRate = curRate;
	}

	public Double getInsuRate() {
		return this.insuRate;
	}

	public void setInsuRate(Double insuRate) {
		this.insuRate = insuRate;
	}

	public String getCcdId() {
		return this.ccdId;
	}

	public void setCcdId(String ccdId) {
		this.ccdId = ccdId;
	}

	public Double getWgtChrg() {
		return this.wgtChrg;
	}

	public void setWgtChrg(Double wgtChrg) {
		this.wgtChrg = wgtChrg;
	}

	public Double getValChrg() {
		return this.valChrg;
	}

	public void setValChrg(Double valChrg) {
		this.valChrg = valChrg;
	}

	public Double getTax() {
		return this.tax;
	}

	public void setTax(Double tax) {
		this.tax = tax;
	}

	public Double getCurConvRate() {
		return this.curConvRate;
	}

	public void setCurConvRate(Double curConvRate) {
		this.curConvRate = curConvRate;
	}

	public Date getAwbDate() {
		return this.awbDate;
	}

	public void setAwbDate(Date awbDate) {
		this.awbDate = awbDate;
	}

	public String getAwbPlace() {
		return this.awbPlace;
	}

	public void setAwbPlace(String awbPlace) {
		this.awbPlace = awbPlace;
	}

	public String getSignShp() {
		return this.signShp;
	}

	public void setSignShp(String signShp) {
		this.signShp = signShp;
	}

	public String getSignAir() {
		return this.signAir;
	}

	public void setSignAir(String signAir) {
		this.signAir = signAir;
	}

	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public String getMrnNo()
	{
		return mrnNo;
	}

	public void setMrnNo(String mrnNo)
	{
		this.mrnNo = mrnNo;
	}

	public Set<ItemAWBAccount> getfAwbAccount() {
		return fAwbAccount;
	}

	public void setfAwbAccount(Set<ItemAWBAccount> fAwbAccount) {
		this.fAwbAccount = fAwbAccount;
	}
	
}