package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * FormularSLI generated by MyEclipse - Hibernate Tools
 */

public class FormularSLI extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 1285472918268694737L;
	transient private Long attId;
	private Sticker sticker;
	private Attachment FAtt;
	private Integer afChrgs;
	private Integer otChrgs;
	private Double valCarr;
	private Double valCust;
	private Double valInsu;
	private String cur3lc;
	private String cuc3lc;
	private Date sliDate;
	private String sign;
	private String card;
	private Date corr;

	// Constructors

	/** default constructor */
	public FormularSLI() {
		
	}

	/** minimal constructor */
	public FormularSLI(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	/** full constructor */
	public FormularSLI(Sticker FStick, Attachment FAtt, Integer afChrgs, Integer otChrgs, Double valCarr, Double valCust, Double valInsu, String cur3lc, String cuc3lc, Date sliDate, String sign, String card, Date corr) {
		this.sticker = FStick;
		this.FAtt = FAtt;
		this.afChrgs = afChrgs;
		this.otChrgs = otChrgs;
		this.valCarr = valCarr;
		this.valCust = valCust;
		this.valInsu = valInsu;
		this.cur3lc = cur3lc;
		this.cuc3lc = cuc3lc;
		this.sliDate = sliDate;
		this.sign = sign;
		this.card = card;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof FormularSLI)) { return false; }
		if (this == obj) { return true; }
		FormularSLI rhs = (FormularSLI) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).toHashCode();
	}
	// Property accessors

	public Long getAttId() {
		return this.attId;
	}

	public void setAttId(Long attId) {
		this.attId = attId;
	}

	public Sticker getSticker() {
		return this.sticker;
	}

	public void setSticker(Sticker FStick) {
		this.sticker = FStick;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public Integer getAfChrgs() {
		return this.afChrgs;
	}

	public void setAfChrgs(Integer afChrgs) {
		this.afChrgs = afChrgs;
	}

	public Integer getOtChrgs() {
		return this.otChrgs;
	}

	public void setOtChrgs(Integer otChrgs) {
		this.otChrgs = otChrgs;
	}

	public Double getValCarr() {
		return this.valCarr;
	}

	public void setValCarr(Double valCarr) {
		this.valCarr = valCarr;
	}

	public Double getValCust() {
		return this.valCust;
	}

	public void setValCust(Double valCust) {
		this.valCust = valCust;
	}

	public Double getValInsu() {
		return this.valInsu;
	}

	public void setValInsu(Double valInsu) {
		this.valInsu = valInsu;
	}

	public String getCur3lc() {
		return this.cur3lc;
	}

	public void setCur3lc(String cur3lc) {
		this.cur3lc = cur3lc;
	}

	public String getCuc3lc() {
		return this.cuc3lc;
	}

	public void setCuc3lc(String cuc3lc) {
		this.cuc3lc = cuc3lc;
	}

	public Date getSliDate() {
		return this.sliDate;
	}

	public void setSliDate(Date sliDate) {
		this.sliDate = sliDate;
	}

	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public String getCard() {
		return this.card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
}