package de.act.central.types;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * HandlingAirportCarrierId generated by MyEclipse - Hibernate Tools
 */

public class HandlingAirportCarrierId extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -6623156905869192192L;
	private String ap3lc;
	private String caId;
	private String service;

	// Constructors

	/** default constructor */
	public HandlingAirportCarrierId() {
		
	}

	/** full constructor */
	public HandlingAirportCarrierId(String ap3lc, String caId, String service) {
		this.ap3lc = ap3lc;
		this.caId = caId;
		this.service = service;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof HandlingAirportCarrierId)) { return false; }
		if (this == obj) { return true; }
		HandlingAirportCarrierId rhs = (HandlingAirportCarrierId) obj;
		return new EqualsBuilder().append(this.ap3lc, rhs.ap3lc).append(this.caId, rhs.caId).append(this.service, rhs.service).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.ap3lc).append(this.caId).append(this.service).toHashCode();
	}

	// Property accessors

	public String getAp3lc() {
		return this.ap3lc;
	}

	public void setAp3lc(String ap3lc) {
		this.ap3lc = ap3lc;
	}

	public String getCaId() {
		return this.caId;
	}

	public void setCaId(String caId) {
		this.caId = caId;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}
}