package de.act.central.types;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * HandlingAirportCarrier generated by MyEclipse - Hibernate Tools
 */

public class HandlingAirportCarrier extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -7335589509451409308L;
	private HandlingAirportCarrierId id;
	private String addId; //HENRY it should either Long or Integer
	private String vadId;

	// Constructors

	/** default constructor */
	public HandlingAirportCarrier() {
		
	}

	/** full constructor */
	public HandlingAirportCarrier(String addId, String vadId) {
		this.addId = addId;
		this.vadId = vadId;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof HandlingAirportCarrier)) { return false; }
		if (this == obj) { return true; }
		HandlingAirportCarrier rhs = (HandlingAirportCarrier) obj;
		return new EqualsBuilder().append(this.id, rhs.id).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.id).toHashCode();
	}
	// Property accessors

	public HandlingAirportCarrierId getId() {
		return this.id;
	}

	public void setId(HandlingAirportCarrierId id) {
		this.id = id;
	}

	public String getAddId() {
		return this.addId;
	}

	public void setAddId(String addId) {
		this.addId = addId;
	}

	public String getVadId() {
		return this.vadId;
	}

	public void setVadId(String vadId) {
		this.vadId = vadId;
	}
}