package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * HandlingInformation generated by MyEclipse - Hibernate Tools
 */

public class HandlingInformation extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -7107298472269394211L;
	transient private Long stick_id;
	private Sticker sticker;
	private Short infoSeq;
	private String infoId;
	private String infoRem;
	private Date corr;
	private String fId;

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.stick_id);
		sb.append(" [");
		sb.append(this.infoSeq);sb.append("], ");
		sb.append(this.infoRem);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public HandlingInformation() {
		
	}

	/** full constructor */
	public HandlingInformation(String infoId, String infoRem, Date corr) {
		this.infoId = infoId;
		this.infoRem = infoRem;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof HandlingInformation)) { return false; }
		if (this == obj) { return true; }
		HandlingInformation rhs = (HandlingInformation) obj;
		return new EqualsBuilder().append(this.sticker, rhs.sticker).append(this.infoSeq, rhs.infoSeq).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.sticker).append(this.infoSeq).toHashCode();
	}

	// Property accessors

	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	public String getInfoRem() {
		return this.infoRem;
	}

	public void setInfoRem(String infoRem) {
		this.infoRem = infoRem;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public Sticker getSticker() {
		return sticker;
	}

	public void setSticker(Sticker stick) {
		sticker = stick;
	}

	public Short getInfoSeq() {
		return infoSeq;
	}

	public void setInfoSeq(Short infoSeq) {
		this.infoSeq = infoSeq;
	}

	public Long getStick_id() {
		return stick_id;
	}

	public void setStick_id(Long stick_id) {
		this.stick_id = stick_id;
	}

	public String getfId() {
		return fId;
	}

	public void setfId(String fId) {
		this.fId = fId;
	}

}