package de.act.central.types;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Manifest generated by MyEclipse - Hibernate Tools
 */

@SuppressWarnings("unchecked")
public class Manifest extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -3320979077616266339L;
	transient private Long maniId;
	private String fltId; //HENRY should be long
	private Date fltDate;
	private Integer creatorAddId;
	private Integer userAddId;
	private Date corr;
	private Date VO;
	private Date closeOut;
	private String statId;
	private String statDescr;
	private Set<ManifestItem> AManiItems = new HashSet(0);

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.maniId);
		sb.append(" [");
		sb.append(this.fltId);sb.append(", ");
		sb.append(this.fltDate);sb.append(", ");
		sb.append(this.creatorAddId);sb.append(", ");
		sb.append(this.userAddId);sb.append(", [");
		sb.append(this.VO);sb.append("], ");
		sb.append(this.statId);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}
	// Constructors

	/** default constructor */
	public Manifest() {
		
	}

	/** full constructor */
	public Manifest(String fltId, Date fltDate, Integer creatorAddId, Integer userAddId, Date corr, Date VO, Date closeOut, String statId, String statDescr, Set AManiItems) {
		this.fltId = fltId;
		this.fltDate = fltDate;
		this.creatorAddId = creatorAddId;
		this.userAddId = userAddId;
		this.corr = corr;
		this.VO = VO;
		this.closeOut = closeOut;
		this.statId = statId;
		this.statDescr = statDescr;
		this.AManiItems = AManiItems;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Manifest)) { return false; }
		if (this == obj) { return true; }
		Manifest rhs = (Manifest) obj;
		return new EqualsBuilder().append(this.fltId, rhs.fltId).append(this.fltDate, rhs.fltDate).append(this.userAddId, rhs.userAddId).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.fltId).append(this.fltDate).append(this.userAddId).toHashCode();
	}

	// Property accessors

	public Long getManiId() {
		return this.maniId;
	}

	public void setManiId(Long maniId) {
		this.maniId = maniId;
	}

	public String getFltId() {
		return this.fltId;
	}

	public void setFltId(String fltId) {
		this.fltId = fltId;
	}

	public Date getFltDate() {
		return this.fltDate;
	}

	public void setFltDate(Date fltDate) {
		this.fltDate = fltDate;
	}

	public Integer getCreatorAddId() {
		return this.creatorAddId;
	}

	public void setCreatorAddId(Integer creatorAddId) {
		this.creatorAddId = creatorAddId;
	}

	public Integer getUserAddId() {
		return this.userAddId;
	}

	public void setUserAddId(Integer userAddId) {
		this.userAddId = userAddId;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public Date getVO() {
		return this.VO;
	}

	public void setVO(Date VO) {
		this.VO = VO;
	}

	public Date getCloseOut() {
		return this.closeOut;
	}

	public void setCloseOut(Date closeOut) {
		this.closeOut = closeOut;
	}

	public String getStatId() {
		return this.statId;
	}

	public void setStatId(String statId) {
		this.statId = statId;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public Set<ManifestItem> getAManiItems() {
		return this.AManiItems;
	}

	public void setAManiItems(Set<ManifestItem> AManiItems) {
		this.AManiItems = AManiItems;
	}
}