package de.act.central.types;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * ManifestItem generated by MyEclipse - Hibernate Tools
 */
public class ManifestItem extends Central implements java.io.Serializable {
	// Fields
	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -8786893680423018755L;
	transient private Long    maniItemId;
	private Uld               AUld;
	private Manifest          AManifest;
	private PackageItemBKG    FBkgItem;
	private Short             maniRow;
	private Short             maniSort;
	private Integer           llPcs;
	private Integer			  llUldID;
	private Long              llUldType;
	private Short             llUldNo;
	private String            llAdvice;
	private String            maniRem;
	private Date              corr;
	private Integer						is_active;
	private Integer						is_loaded;
	

	private Set<AcceptanceItem> shpItems = new HashSet<AcceptanceItem>(0);

	
	public Integer getIs_active() {
		return is_active;
	}

	public void setIs_active(Integer is_active) {
		this.is_active = is_active;
	}
	
	public Integer getIs_loaded() {
		return is_loaded;
	}

	public void setIs_loaded(Integer is_loaded) {
		this.is_loaded = is_loaded;
	}
	
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.maniItemId);
		sb.append(" [");
		sb.append(this.maniRow);sb.append(", ");
		sb.append(this.llPcs);sb.append(", ");
		sb.append(this.llUldNo);sb.append(", ");
		sb.append(this.llUldType);sb.append(", [");
		sb.append(this.AUld);sb.append("], ");
		sb.append(this.maniRem);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors
	/** default constructor */
	public ManifestItem() {
		
	}

	/** minimal constructor */
	public ManifestItem(Manifest AManifest, Short maniRow, Short maniSort) {
		this.AManifest = AManifest;
		this.maniRow = maniRow;
		this.maniSort = maniSort;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof ManifestItem)){
			return false;
		}
		if (this == obj){
			return true;
		}
		ManifestItem rhs = (ManifestItem) obj;
		return new EqualsBuilder().append(this.AManifest, rhs.AManifest).append(this.maniRow, rhs.maniRow).isEquals();
	}

	/**
	 * 12.12.2005
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.AManifest).append(this.maniRow).toHashCode();
	}

	// Property accessors
	public Long getManiItemId() {
		return this.maniItemId;
	}

	public void setManiItemId(Long maniItemId) {
		this.maniItemId = maniItemId;
	}

	public Uld getAUld() {
		return this.AUld;
	}

	public void setAUld(Uld AUld) {
		this.AUld = AUld;
	}

	public Manifest getAManifest() {
		return this.AManifest;
	}

	public void setAManifest(Manifest AManifest) {
		this.AManifest = AManifest;
	}

	public PackageItemBKG getFBkgItem() {
		return this.FBkgItem;
	}

	public void setFBkgItem(PackageItemBKG FBkgItem) {
		this.FBkgItem = FBkgItem;
	}

	public Short getManiRow() {
		return this.maniRow;
	}

	public void setManiRow(Short maniRow) {
		this.maniRow = maniRow;
	}

	public Short getManiSort() {
		return this.maniSort;
	}

	public void setManiSort(Short maniSort) {
		this.maniSort = maniSort;
	}

	public Integer getLlPcs() {
		return this.llPcs;
	}

	public void setLlPcs(Integer llPcs) {
		this.llPcs = llPcs;
	}

	public Integer getLlUldID() {
		return llUldID;
	}

	public void setLlUldID(Integer llUldID) {
		this.llUldID = llUldID;
	}

	public Long getLlUldType() {
		return this.llUldType;
	}

	public void setLlUldType(Long llUldType) {
		this.llUldType = llUldType;
	}

	public Short getLlUldNo() {
		return this.llUldNo;
	}

	public void setLlUldNo(Short llUldNo) {
		this.llUldNo = llUldNo;
	}

	public String getLlAdvice() {
		return this.llAdvice;
	}

	public void setLlAdvice(String llAdvice) {
		this.llAdvice = llAdvice;
	}

	public String getManiRem() {
		return this.maniRem;
	}

	public void setManiRem(String maniRem) {
		this.maniRem = maniRem;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
	
	public Set<AcceptanceItem> getShpItems() {
		return shpItems;
	}

	public void setShpItems(Set<AcceptanceItem> shpItems) {
		this.shpItems = shpItems;
	}
}
