package de.act.central.types;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * PackageItemAWB generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings({"unused", "unchecked"})
public class PackageItemAWB extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 3305360000447821434L;
	transient private Long awbItemId;
	private Attachment FAtt;
	private Short awbRow;
	private Short linkRow;
	private Integer pcs;
	private Double wgt;
	private String serviceCode;
	private String rateType;
	private String rateClass;
	private String classType;
	private String itemNo;
	private Double chrgblWgt;
	private Double rate;
	private Double rateFactor;
	private Double total;
	private String rateId;
	private Date corr;
	private Set<PackageItem> FPkgs = new HashSet<PackageItem>(0);
	private String cur3lcFrom;
	private String cur3lcTo;
	private Double conversionRate;

	// Constructors

	/** default constructor */
	public PackageItemAWB() {
		
	}

	/** full constructor */
	public PackageItemAWB(Attachment FAtt, Short awbRow, Short linkRow, Integer pcs, Double wgt, String serviceCode, String rateType, String rateClass, 
			String classType, String itemNo, Double chrgblWgt, Double rate, Double rateFactor, Double total, String rateId, Date corr, Set FPkgs,
			String cur3lcFrom, String cur3lcTo, Double conversionRate) {
		this.FAtt = FAtt;
		this.awbRow = awbRow;
		this.linkRow = linkRow;
		this.pcs = pcs;
		this.wgt = wgt;
		this.serviceCode = serviceCode;
		this.rateType = rateType;
		this.rateClass = rateClass;
		this.classType = classType;
		this.itemNo = itemNo;
		this.chrgblWgt = chrgblWgt;
		this.rate = rate;
		this.rateFactor = rateFactor;
		this.total = total;
		this.rateId = rateId;
		this.corr = corr;
		this.FPkgs = FPkgs;
		this.cur3lcFrom = cur3lcFrom;
		this.cur3lcTo = cur3lcTo;
		this.conversionRate = conversionRate;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof PackageItemAWB)) { return false; }
		if (this == obj) { return true; }
		PackageItemAWB rhs = (PackageItemAWB) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.awbRow, rhs.awbRow).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.awbRow).toHashCode();
	}
	// Property accessors

	public Long getAwbItemId() {
		return this.awbItemId;
	}

	public void setAwbItemId(Long awbItemId) {
		this.awbItemId = awbItemId;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public Short getAwbRow() {
		return this.awbRow;
	}

	public void setAwbRow(Short awbRow) {
		this.awbRow = awbRow;
	}

	public Short getLinkRow() {
		return this.linkRow;
	}

	public void setLinkRow(Short linkRow) {
		this.linkRow = linkRow;
	}

	public Integer getPcs() {
		return this.pcs;
	}

	public void setPcs(Integer pcs) {
		this.pcs = pcs;
	}

	public Double getWgt() {
		return this.wgt;
	}

	public void setWgt(Double wgt) {
		this.wgt = wgt;
	}

	public String getServiceCode() {
		return this.serviceCode;
	}

	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	public String getRateType() {
		return this.rateType;
	}

	public void setRateType(String rateType) {
		this.rateType = rateType;
	}

	public String getRateClass() {
		return this.rateClass;
	}

	public void setRateClass(String rateClass) {
		this.rateClass = rateClass;
	}

	public String getClassType() {
		return this.classType;
	}

	public void setClassType(String classType) {
		this.classType = classType;
	}

	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	public Double getChrgblWgt() {
		return this.chrgblWgt;
	}

	public void setChrgblWgt(Double chrgblWgt) {
		this.chrgblWgt = chrgblWgt;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Double getRateFactor() {
		return this.rateFactor;
	}

	public void setRateFactor(Double rateFactor) {
		this.rateFactor = rateFactor;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public String getRateId() {
		return this.rateId;
	}

	public void setRateId(String rateId) {
		this.rateId = rateId;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public String getCur3lcFrom() {
		return cur3lcFrom;
	}

	public void setCur3lcFrom(String cur3lcFrom) {
		this.cur3lcFrom = cur3lcFrom;
	}

	public String getCur3lcTo() {
		return cur3lcTo;
	}

	public void setCur3lcTo(String cur3lcTo) {
		this.cur3lcTo = cur3lcTo;
	}

	public Double getConversionRate() {
		return conversionRate;
	}

	public void setConversionRate(Double conversionRate) {
		this.conversionRate = conversionRate;
	}

	//    public Set<PackageItem> getFPkgs() {
	//        return this.FPkgs;
	//    }
	//
	//    public void setFPkgs(Set<PackageItem> FPkgs) {
	//        this.FPkgs = FPkgs;
	//    }
}