package de.act.central.types;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * PackageItem generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("unchecked")
public class PackageItem2 extends Central implements java.io.Serializable {
	// Fields
	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long   serialVersionUID = -6768693917173615429L;
	transient private Long      pkgId;
	private PackageItemAWB      FAwbItem;
	private Sticker             sticker;
	private Uld                 AUld;
	private Attachment2          FAtt;
	private PackageItemBKG2      FBkgItem;
	private PackageItemSLI      FSliItem;
	private PackageItemDGR      FDgrItem;
	private PackageItemAVI      FAviItem;
	private Short               rowNo;
	private String              marks;
	private Integer             pcs;
	private Integer             pkgsPltsd;
	private String              pkgsCol;
	private String              pkgsMat;
	private String              pkgsShp;
	private Long              	comId;
	private Long                annId;
	private Double              wgt;
	private Long                l;
	private Long                w;
	private Long                h;
	private Double			  	vol;
	private String              scc3lc;
	private Date                corr;
	private Integer 			pcsDelivered; 
	private Set<PackageState>   FPkgStats        = new HashSet<PackageState>(0);
	private Set<PackageItemAVI> FAviItems        = new HashSet<PackageItemAVI>(0);
	private Set<PackageItemDGR> FDgrItems        = new HashSet<PackageItemDGR>(0);
	private Set<AcceptanceItem> FAccPkgs         = new HashSet<AcceptanceItem>(0);

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.pkgId);
		sb.append(" [");
		sb.append(this.rowNo);sb.append(", ");
		sb.append(this.pcs);sb.append(", ");
		sb.append(this.wgt);sb.append(", ");
		sb.append(this.comId);sb.append(", [");
		sb.append(this.AUld);sb.append("], ");
		sb.append(this.scc3lc);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors
	/** default constructor */
	public PackageItem2() {

	}

	/** full constructor */
	public PackageItem2(PackageItemAWB FAwbItem, Sticker FStick, Uld AUld, Attachment2 FAtt, PackageItemBKG2 FBkgItem, Short rowNo, String marks, Integer pcs, Integer pkgsPltsd, String pkgsCol,
			String pkgsMat, String pkgsShp, Long comId, Long annId, Double wgt, Long l, Long w, Long h, String scc3lc, Date corr, Set FPkgStats, Set FAviItems, Set FDgrItems, Set FAccPkgs) {
		this.FAwbItem = FAwbItem;
		this.sticker = FStick;
		this.AUld = AUld;
		this.FAtt = FAtt;
		this.FBkgItem = FBkgItem;
		this.rowNo = rowNo;
		this.marks = marks;
		this.pcs = pcs;
		this.pkgsPltsd = pkgsPltsd;
		this.pkgsCol = pkgsCol;
		this.pkgsMat = pkgsMat;
		this.pkgsShp = pkgsShp;
		this.comId = comId;
		this.annId = annId;
		this.wgt = wgt;
		this.l = l;
		this.w = w;
		this.h = h;
		this.scc3lc = scc3lc;
		this.corr = corr;
		this.FPkgStats = FPkgStats;
		this.FAviItems = FAviItems;
		this.FDgrItems = FDgrItems;
		this.FAccPkgs = FAccPkgs;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof PackageItem2)){
			return false;
		}
		if (this == obj){
			return true;
		}
		PackageItem2 rhs = (PackageItem2) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.rowNo, rhs.rowNo).isEquals();
	}

	/**
	 * 12.12.2005
	 * 
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.rowNo).toHashCode();
	}

	// Property accessors
	public Long getPkgId() {
		return this.pkgId;
	}

	public void setPkgId(Long pkgId) {
		this.pkgId = pkgId;
	}

	public PackageItemAWB getFAwbItem() {
		return this.FAwbItem;
	}

	public void setFAwbItem(PackageItemAWB FAwbItem) {
		this.FAwbItem = FAwbItem;
	}

	public Sticker getSticker() {
		return this.sticker;
	}

	public void setSticker(Sticker FStick) {
		this.sticker = FStick;
	}

	public Uld getAUld() {
		return this.AUld;
	}

	public void setAUld(Uld AUld) {
		this.AUld = AUld;
	}

	public Attachment2 getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment2 FAtt) {
		this.FAtt = FAtt;
	}

	public PackageItemBKG2 getFBkgItem() {
		return this.FBkgItem;
	}

	public void setFBkgItem(PackageItemBKG2 FBkgItem) {
		this.FBkgItem = FBkgItem;
	}

	public Short getRowNo() {
		return this.rowNo;
	}

	public void setRowNo(Short rowNo) {
		this.rowNo = rowNo;
	}

	public String getMarks() {
		return this.marks;
	}

	public void setMarks(String marks) {
		this.marks = marks;
	}

	public Integer getPcs() {
		return this.pcs;
	}

	public void setPcs(Integer pcs) {
		this.pcs = pcs;
	}

	public Integer getPkgsPltsd() {
		return this.pkgsPltsd;
	}

	public void setPkgsPltsd(Integer pkgsPltsd) {
		this.pkgsPltsd = pkgsPltsd;
	}

	public String getPkgsCol() {
		return this.pkgsCol;
	}

	public void setPkgsCol(String pkgsCol) {
		this.pkgsCol = pkgsCol;
	}

	public String getPkgsMat() {
		return this.pkgsMat;
	}

	public void setPkgsMat(String pkgsMat) {
		this.pkgsMat = pkgsMat;
	}

	public String getPkgsShp() {
		return this.pkgsShp;
	}

	public void setPkgsShp(String pkgsShp) {
		this.pkgsShp = pkgsShp;
	}

	public Long getComId() {
		return this.comId;
	}

	public void setComId(Long comId) {
		this.comId = comId;
	}

	public Long getAnnId() {
		return this.annId;
	}

	public void setAnnId(Long annId) {
		this.annId = annId;
	}

	public Double getWgt() {
		return this.wgt;
	}

	public void setWgt(Double wgt) {
		this.wgt = wgt;
	}

	public Long getL() {
		return this.l;
	}

	public void setL(Long l) {
		this.l = l;
	}

	public Long getW() {
		return this.w;
	}

	public void setW(Long w) {
		this.w = w;
	}

	public Long getH() {
		return this.h;
	}

	public void setH(Long h) {
		this.h = h;
	}

	public String getScc3lc() {
		return this.scc3lc;
	}

	public void setScc3lc(String scc3lc) {
		this.scc3lc = scc3lc;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
	// public Set getFPkgStats() {
	// return this.FPkgStats;
	// }
	//
	// public void setFPkgStats(Set FPkgStats) {
	// this.FPkgStats = FPkgStats;
	// }
	// public Set getFAviItems() {
	// return this.FAviItems;
	// }
	//
	// public void setFAviItems(Set FAviItems) {
	// this.FAviItems = FAviItems;
	// }
	// public Set getFDgrItems() {
	// return this.FDgrItems;
	// }
	//
	// public void setFDgrItems(Set FDgrItems) {
	// this.FDgrItems = FDgrItems;
	// }
	//
	// public Set getFAccPkgs() {
	// return this.FAccPkgs;
	// }
	//
	// public void setFAccPkgs(Set FAccPkgs) {
	// this.FAccPkgs = FAccPkgs;
	// }

	public Set<AcceptanceItem> getFAccPkgs() {
		return FAccPkgs;
	}

	public void setFAccPkgs(Set<AcceptanceItem> accPkgs) {
		FAccPkgs = accPkgs;
	}

	public PackageItemAVI getFAviItem() {
		return FAviItem;
	}

	public void setFAviItem(PackageItemAVI aviItem) {
		FAviItem = aviItem;
	}

	public Set<PackageItemAVI> getFAviItems() {
		return FAviItems;
	}

	public void setFAviItems(Set<PackageItemAVI> aviItems) {
		FAviItems = aviItems;
	}

	public PackageItemDGR getFDgrItem() {
		return FDgrItem;
	}

	public void setFDgrItem(PackageItemDGR dgrItem) {
		FDgrItem = dgrItem;
	}

	public Set<PackageItemDGR> getFDgrItems() {
		return FDgrItems;
	}

	public void setFDgrItems(Set<PackageItemDGR> dgrItems) {
		FDgrItems = dgrItems;
	}

	public Set<PackageState> getFPkgStats() {
		return FPkgStats;
	}

	public void setFPkgStats(Set<PackageState> pkgStats) {
		FPkgStats = pkgStats;
	}

	public PackageItemSLI getFSliItem() {
		return FSliItem;
	}

	public void setFSliItem(PackageItemSLI sliItem) {
		FSliItem = sliItem;
	}

	public Integer getPcsDelivered() {
		return pcsDelivered;
	}

	public void setPcsDelivered(Integer pcsDelivered) {
		this.pcsDelivered = pcsDelivered;
	}

	public Double getVol() {
		return vol;
	}

	public void setVol(Double vol) {
		this.vol = vol;
	}
}