package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * PackageItemDGR generated by MyEclipse - Hibernate Tools
 */

public class PackageItemDGR extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 1653385596020458158L;
	transient private Long dgrItemId;
	private Attachment FAtt;
	private Short dgrRowNo;
	private Long page;
	private String dgrId;
	private String pkgType;
	private String pkgInst;
	private Long pcsNo;
	private Double qty;
	private String unitId;
	private Date corr;

	// Constructors

	/** default constructor */
	public PackageItemDGR() {
		
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof PackageItemDGR)) { return false; }
		if (this == obj) { return true; }
		PackageItemDGR rhs = (PackageItemDGR) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.dgrRowNo, rhs.dgrRowNo).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.dgrRowNo).toHashCode();
	}

	// Property accessors

	public Long getDgrItemId() {
		return this.dgrItemId;
	}

	public void setDgrItemId(Long dgrItemId) {
		this.dgrItemId = dgrItemId;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public Short getDgrRowNo() {
		return this.dgrRowNo;
	}

	public void setDgrRowNo(Short dgrRowNo) {
		this.dgrRowNo = dgrRowNo;
	}

	public Long getPage() {
		return this.page;
	}

	public void setPage(Long page) {
		this.page = page;
	}

	public String getDgrId() {
		return this.dgrId;
	}

	public void setDgrId(String dgrId) {
		this.dgrId = dgrId;
	}

	public String getPkgType() {
		return this.pkgType;
	}

	public void setPkgType(String pkgType) {
		this.pkgType = pkgType;
	}

	public String getPkgInst() {
		return this.pkgInst;
	}

	public void setPkgInst(String pkgInst) {
		this.pkgInst = pkgInst;
	}

	public Long getPcsNo() {
		return this.pcsNo;
	}

	public void setPcsNo(Long pcsNo) {
		this.pcsNo = pcsNo;
	}

	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
}