package de.act.central.types;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;


/**
 * PackageItemBKG generated by MyEclipse - Hibernate Tools
 */
@SuppressWarnings("unused")
public class PackageItemBKG2 extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 7937774336726123875L;
	transient private Long bkgItemId;
	private Attachment2 FAtt;
	private Long att_id;
	private Short part;
	private Integer pcs;
	private Double wgt;
	private Double vol;
	private Long comId;
	private Long annId;
	private String scc3lc;
	private Date corr;
	private Date reqDep;
	private Date reqArr;
	private String reqCaId;
	private Short reqHops;
	private String reqFrom;
	private String reqTo;
	private String reqStat;
	private Short prio;
	private Set<PackageItem> FPkgs = new HashSet<PackageItem>(0);
	//private Set<BookingFlight> FBkgFlts = new HashSet(0);
	private Set<ManifestItem> AManiItems = new HashSet<ManifestItem>(0);
	
	private Integer isParent;

	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.bkgItemId);
		sb.append(" [");
		sb.append(this.part);sb.append(", ");
		sb.append(this.pcs);sb.append(", ");
		sb.append(this.wgt);sb.append(", ");
		sb.append(this.comId);sb.append(", ");
		sb.append(this.reqStat);sb.append(", ");
		sb.append(this.reqFrom);sb.append(", ");
		sb.append(this.reqTo);sb.append(", ");
		sb.append(this.reqHops);sb.append(", ");
		sb.append(this.reqCaId);sb.append(", ");
		sb.append(this.reqDep);sb.append(", ");
		sb.append(this.reqArr);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public PackageItemBKG2() {
		
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof PackageItemBKG2)) { return false; }
		if (this == obj) { return true; }
		PackageItemBKG2 rhs = (PackageItemBKG2) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.part, rhs.part).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.part).toHashCode();
	}

	// Property accessors

	public Long getBkgItemId() {
		return this.bkgItemId;
	}

	public void setBkgItemId(Long bkgItemId) {
		this.bkgItemId = bkgItemId;
	}

	public Attachment2 getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment2 FAtt) {
		this.FAtt = FAtt;
	}

	public Long getAtt_id() {
		return att_id;
	}

	public void setAtt_id(Long att_id) {
		this.att_id = att_id;
	}

	public Short getPart() {
		return this.part;
	}

	public void setPart(Short part) {
		this.part = part;
	}

	public Integer getPcs() {
		return this.pcs;
	}

	public void setPcs(Integer pcs) {
		this.pcs = pcs;
	}

	public Double getWgt() {
		return this.wgt;
	}

	public void setWgt(Double wgt) {
		this.wgt = wgt;
	}

	public Double getVol() {
		return this.vol;
	}

	public void setVol(Double vol) {
		this.vol = vol;
	}

	public Long getComId() {
		return this.comId;
	}

	public void setComId(Long comId) {
		this.comId = comId;
	}

	public Long getAnnId() {
		return this.annId;
	}

	public void setAnnId(Long annId) {
		this.annId = annId;
	}

	public String getScc3lc() {
		return this.scc3lc;
	}

	public void setScc3lc(String scc3lc) {
		this.scc3lc = scc3lc;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public Date getReqDep() {
		return this.reqDep;
	}

	public void setReqDep(Date reqDep) {
		this.reqDep = reqDep;
	}

	public Date getReqArr() {
		return this.reqArr;
	}

	public void setReqArr(Date reqArr) {
		this.reqArr = reqArr;
	}

	public String getReqCaId() {
		return this.reqCaId;
	}

	public void setReqCaId(String reqCaId) {
		this.reqCaId = reqCaId;
	}

	public Short getReqHops() {
		return this.reqHops;
	}

	public void setReqHops(Short reqHops) {
		this.reqHops = reqHops;
	}

	public String getReqFrom() {
		return this.reqFrom;
	}

	public void setReqFrom(String reqFrom) {
		this.reqFrom = reqFrom;
	}

	public String getReqTo() {
		return this.reqTo;
	}

	public void setReqTo(String reqTo) {
		this.reqTo = reqTo;
	}

	public String getReqStat() {
		return this.reqStat;
	}

	public void setReqStat(String reqStat) {
		this.reqStat = reqStat;
	}

	public Integer getIsParent() {
		return isParent;
	}

	public void setIsParent(Integer isParent) {
		this.isParent = isParent;
	}

	public Short getPrio()
	{
		return prio;
	}

	public void setPrio(Short prio)
	{
		this.prio = prio;
	}

	//    public Set getFPkgs() {
	//        return this.FPkgs;
	//    }
	//
	//    public void setFPkgs(Set FPkgs) {
	//        this.FPkgs = FPkgs;
	//    }
	//    public Set<BookingFlight> getFBkgFlts() {
	//        return this.FBkgFlts;
	//    }
	//
	//    public void setFBkgFlts(Set<BookingFlight> FBkgFlts) {
	//        this.FBkgFlts = FBkgFlts;
	//    }
	//    public Set getAManiItems() {
	//        return this.AManiItems;
	//    }
	//
	//    public void setAManiItems(Set AManiItems) {
	//        this.AManiItems = AManiItems;
	//    }
}