package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * PackageState generated by MyEclipse - Hibernate Tools
 */

public class PackageState extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -3725824523711774238L;
	transient private Long pkgStatId;
	private Attachment FAtt;
	private PackageItem FPkg;
	private String pkgStatus;
	private String statDescr;
	private String addId; //HENRY it should either Long or Integer
	private Date corr;

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.pkgStatId);
		sb.append(" [");
		sb.append(this.pkgStatus);sb.append(", ");
		sb.append(this.statDescr);sb.append(", ");
		sb.append(this.addId);sb.append(", ");
		sb.append(this.corr);
		sb.append("]");
		return sb.toString();
	}

	// Constructors

	/** default constructor */
	public PackageState() {
		
	}

	/** full constructor */
	public PackageState(Attachment FAtt, PackageItem FPkg, String pkgStatus, String statDescr, String addId, Date corr) {
		this.FAtt = FAtt;
		this.FPkg = FPkg;
		this.pkgStatus = pkgStatus;
		this.statDescr = statDescr;
		this.addId = addId;
		this.corr = corr;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof PackageState)) { return false; }
		if (this == obj) { return true; }
		PackageState rhs = (PackageState) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.FPkg, rhs.FPkg).append(this.pkgStatus, rhs.pkgStatus).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.FPkg).append(this.pkgStatus).toHashCode();
	}

	// Property accessors

	public Long getPkgStatId() {
		return this.pkgStatId;
	}

	public void setPkgStatId(Long pkgStatId) {
		this.pkgStatId = pkgStatId;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public PackageItem getFPkg() {
		return this.FPkg;
	}

	public void setFPkg(PackageItem FPkg) {
		this.FPkg = FPkg;
	}

	public String getPkgStatus() {
		return this.pkgStatus;
	}

	public void setPkgStatus(String pkgStatus) {
		this.pkgStatus = pkgStatus;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public String getAddId() {
		return this.addId;
	}

	public void setAddId(String addId) {
		this.addId = addId;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}
}