package de.act.central.types;

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Routing generated by MyEclipse - Hibernate Tools
 */

public class Routing extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = -3697056345048103513L;
	transient private Long rtId;
	private Attachment FAtt;
	private Long rtSeq;
	private Date corr;
	private String ap3lc;
	private boolean isContains = false;
	

	// Constructors

	/** default constructor */
	public Routing() {
		
	}

	/** full constructor */
	public Routing(Attachment FAtt, Long rtSeq, Date corr, String ap3lc) {
		this.FAtt = FAtt;
		this.rtSeq = rtSeq;
		this.corr = corr;
		this.ap3lc = ap3lc;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Routing)) { return false; }
		if (this == obj) { return true; }
		Routing rhs = (Routing) obj;
		return new EqualsBuilder().append(this.FAtt, rhs.FAtt).append(this.rtSeq, rhs.rtSeq).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FAtt).append(this.rtSeq).toHashCode();
	}

	// Property accessors

	public Long getRtId() {
		return this.rtId;
	}

	public void setRtId(Long rtId) {
		this.rtId = rtId;
	}

	public Attachment getFAtt() {
		return this.FAtt;
	}

	public void setFAtt(Attachment FAtt) {
		this.FAtt = FAtt;
	}

	public Long getRtSeq() {
		return this.rtSeq;
	}

	public void setRtSeq(Long rtSeq) {
		this.rtSeq = rtSeq;
	}

	public Date getCorr() {
		return this.corr;
	}

	public void setCorr(Date corr) {
		this.corr = corr;
	}

	public String getAp3lc() {
		return this.ap3lc;
	}

	public void setAp3lc(String ap3lc) {
		this.ap3lc = ap3lc;
	}

	public boolean isContains() {
		return isContains;
	}

	public void setContains(boolean isContains) {
		this.isContains = isContains;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	 @Override
	 public String toString() {
		 StringBuffer sb = new StringBuffer();
		 sb.append(this.rtId);
		 sb.append(" [");
		 sb.append(this.rtSeq);sb.append(", ");
		 sb.append(this.ap3lc);sb.append(", ");
		 sb.append(this.corr);
		 sb.append("]");
		 return sb.toString();
	 }
}