package de.act.central.types;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * SubtTCom generated by MyEclipse - Hibernate Tools
 */

public class SubtTCom extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 2058766038299816727L;
	private SubtTComId id;
	private String subtTcomNo;

	// Constructors

	/** default constructor */
	public SubtTCom() {
		
	}

	/** full constructor */
	public SubtTCom(String subtTcomNo) {
		this.subtTcomNo = subtTcomNo;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof SubtTCom)) { return false; }
		if (this == obj) { return true; }
		SubtTCom rhs = (SubtTCom) obj;
		return new EqualsBuilder().append(this.id, rhs.id).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.id).toHashCode();
	}

	// Property accessors

	public SubtTComId getId() {
		return this.id;
	}

	public void setId(SubtTComId id) {
		this.id = id;
	}

	public String getSubtTcomNo() {
		return this.subtTcomNo;
	}

	public void setSubtTcomNo(String subtTcomNo) {
		this.subtTcomNo = subtTcomNo;
	}
}