package de.act.central.types;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * SubtTComId generated by MyEclipse - Hibernate Tools
 */

public class SubtTComId extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 2173922238939128364L;
	private CentralSubt FSubt;
	private String subtTcomType;

	// Constructors

	/** default constructor */
	public SubtTComId() {
		
	}

	/** full constructor */
	public SubtTComId(CentralSubt FSubt, String subtTcomType) {
		this.FSubt = FSubt;
		this.subtTcomType = subtTcomType;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof SubtTComId)) { return false; }
		if (this == obj) { return true; }
		SubtTComId rhs = (SubtTComId) obj;
		return new EqualsBuilder().append(this.FSubt, rhs.FSubt).append(this.subtTcomType, rhs.subtTcomType).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.FSubt).append(this.subtTcomType).toHashCode();
	}

	// Property accessors

	public CentralSubt getFSubt() {
		return this.FSubt;
	}

	public void setFSubt(CentralSubt FSubt) {
		this.FSubt = FSubt;
	}

	public String getSubtTcomType() {
		return this.subtTcomType;
	}

	public void setSubtTcomType(String subtTcomType) {
		this.subtTcomType = subtTcomType;
	}
}