package de.act.central.types;

/**
 * TransferUld generated by MyEclipse - Hibernate Tools
 */

public class TransferUld extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 2585109895197338324L;
	transient private Long uldId;
	private String uldTransMode;
	private String uldDest;
	private Long uldUser;
	private Long uldConsignee;

	// Constructors

	/** default constructor */
	public TransferUld() {
		
	}

	/** minimal constructor */
	public TransferUld(String uldTransMode) {
		this.uldTransMode = uldTransMode;
	}

	/** full constructor */
	public TransferUld(String uldTransMode, String uldDest, Long uldUser, Long uldConsignee) {
		this.uldTransMode = uldTransMode;
		this.uldDest = uldDest;
		this.uldUser = uldUser;
		this.uldConsignee = uldConsignee;
	}

	// Property accessors

	public Long getUldId() {
		return this.uldId;
	}

	public void setUldId(Long uldId) {
		this.uldId = uldId;
	}

	public String getUldTransMode() {
		return this.uldTransMode;
	}

	public void setUldTransMode(String uldTransMode) {
		this.uldTransMode = uldTransMode;
	}

	public String getUldDest() {
		return this.uldDest;
	}

	public void setUldDest(String uldDest) {
		this.uldDest = uldDest;
	}

	public Long getUldUser() {
		return this.uldUser;
	}

	public void setUldUser(Long uldUser) {
		this.uldUser = uldUser;
	}

	public Long getUldConsignee() {
		return this.uldConsignee;
	}

	public void setUldConsignee(Long uldConsignee) {
		this.uldConsignee = uldConsignee;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	 @Override
	 public String toString() {
		 StringBuffer sb = new StringBuffer();
		 sb.append(this.uldId);
		 sb.append(" [");
		 sb.append(this.uldTransMode);sb.append(", ");
		 sb.append(this.uldDest);sb.append(", ");
		 sb.append(this.uldUser);sb.append(", ");
		 sb.append(this.uldConsignee);
		 sb.append("]");
		 return sb.toString();
	 }
}