package de.act.central.types;

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Uld generated by MyEclipse - Hibernate Tools
 */

public class Uld extends Central implements java.io.Serializable {

	// Fields

	/**
	 * @author Martin Sachs
	 * @since 1.0 - 20.11.2006
	 */
	private static final long serialVersionUID = 7146247130081775022L;
	transient private Long uldId;
	private String uldPrefix;
	private String uldNo;
	private String caId;
	//private Long uldTypeId;
	private Long SUldID;
	private Integer discrId;
	private String uldRem;
	private Integer ownerAddId; //HENRY it should Long or Integer
	private Integer holderAddId;
	private Integer isUsed;
	private String statId;
	private String statDescr;
	private Integer locId;
	private Set<ManifestItem> AManiItems = new HashSet<ManifestItem>(0);
	private Set<PackageItem> FPkgs = new HashSet<PackageItem>(0);
	private Set<AcceptanceItem> FAccItems = new HashSet<AcceptanceItem>(0);

	// Constructors

	/** default constructor */
	public Uld() {
		
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (!(obj instanceof Uld)) { return false; }
		if (this == obj) { return true; }
		Uld rhs = (Uld) obj;
		return new EqualsBuilder().append(this.uldPrefix, rhs.uldPrefix).append(this.uldNo, rhs.uldNo).append(this.caId, rhs.caId).isEquals();
	}

	/**
	 * 12.12.2005
	 *
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(this.uldPrefix).append(this.uldNo).append(this.caId).toHashCode();
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(this.uldId);
		sb.append(" [");
		sb.append(this.uldPrefix);sb.append(", ");
		sb.append(this.uldNo);sb.append(", ");
		sb.append(this.caId);
		sb.append("]");
		return sb.toString();
	}

	// Property accessors

	public Long getUldId() {
		return this.uldId;
	}

	public void setUldId(Long uldId) {
		this.uldId = uldId;
	}

	public String getUldPrefix() {
		return this.uldPrefix;
	}

	public void setUldPrefix(String uldPrefix) {
		this.uldPrefix = uldPrefix;
	}

	public String getUldNo() {
		return this.uldNo;
	}

	public void setUldNo(String uldNo) {
		this.uldNo = uldNo;
	}

	public String getCaId() {
		return this.caId;
	}

	public void setCaId(String caId) {
		this.caId = caId;
	}

	public Long getSUldID() {
		return SUldID;
	}

	public void setSUldID(Long uldID) {
		SUldID = uldID;
	}

	public Integer getDiscrId() {
		return this.discrId;
	}

	public void setDiscrId(Integer discrId) {
		this.discrId = discrId;
	}

	public String getUldRem() {
		return this.uldRem;
	}

	public void setUldRem(String uldRem) {
		this.uldRem = uldRem;
	}

	public Integer getOwnerAddId() {
		return this.ownerAddId;
	}

	public void setOwnerAddId(Integer ownerAddId) {
		this.ownerAddId = ownerAddId;
	}

	public Integer getHolderAddId() {
		return this.holderAddId;
	}

	public void setHolderAddId(Integer holderAddId) {
		this.holderAddId = holderAddId;
	}

	public Integer getIsUsed() {
		return isUsed;
	}

	public void setIsUsed(Integer isUsed) {
		this.isUsed = isUsed;
	}

	public String getStatId() {
		return this.statId;
	}

	public void setStatId(String statId) {
		this.statId = statId;
	}

	public String getStatDescr() {
		return this.statDescr;
	}

	public void setStatDescr(String statDescr) {
		this.statDescr = statDescr;
	}

	public Integer getLocId() {
		return this.locId;
	}

	public void setLocId(Integer locId) {
		this.locId = locId;
	}

	public Set<ManifestItem> getAManiItems() {
		return this.AManiItems;
	}

	public void setAManiItems(Set<ManifestItem> AManiItems) {
		this.AManiItems = AManiItems;
	}

	public Set<PackageItem> getFPkgs() {
		return this.FPkgs;
	}

	public void setFPkgs(Set<PackageItem> FPkgs) {
		this.FPkgs = FPkgs;
	}

	public Set<AcceptanceItem> getFAccItems() {
		return this.FAccItems;
	}

	public void setFAccItems(Set<AcceptanceItem> FAccItems) {
		this.FAccItems = FAccItems;
	}
}